// Banque de questions DEA Ambulancier
// Contenu à visée pédagogique — sources : référentiel DEA (arrêté 26/01/2006 modifié),
// recommandations SFMU / CFRC / GFRUP / OMS pour la partie gestes d'urgence.
// Ne remplace pas un cours officiel.

import type { Unit, Question } from "./curriculum";

// tuple: [idSuffix, question, choices[], correctIndex, explanation?]
type QT = [string, string, string[], number, string?];

const mk = (unitId: string, lessonId: string, items: QT[]): Question[] =>
  items.map(([suf, question, choices, answer, explanation]) => ({
    id: `${lessonId}-${suf}`,
    type: "mcq" as const,
    prompt: "Choisis la bonne réponse",
    question,
    choices,
    answer,
    explanation,
  }));

// ============================================================
// UNITÉ 1 — HYGIÈNE, ASEPSIE, RISQUES INFECTIEUX
// ============================================================
const HYGIENE: Unit = {
  id: "dea-hygiene",
  title: "Hygiène & asepsie",
  subtitle: "Prévenir la transmission",
  color: "success",
  icon: "🧼",
  lessons: [
    {
      id: "dea-hyg-1",
      title: "Précautions standard",
      emoji: "🧴",
      questions: mk("dea-hygiene", "dea-hyg-1", [
        ["1", "La friction hydro-alcoolique dure au minimum :", ["5 secondes", "15 secondes", "30 secondes", "2 minutes"], 2, "Durée minimale recommandée : 30 s jusqu'à séchage complet."],
        ["2", "Les précautions standard s'appliquent :", ["Uniquement en cas de patient contagieux connu", "À tout patient, tout le temps", "Seulement au bloc opératoire", "Uniquement en réanimation"], 1, "Elles s'appliquent quel que soit le statut infectieux du patient."],
        ["3", "Avant une friction hydro-alcoolique, les mains doivent être :", ["Mouillées", "Sèches et non souillées", "Savonnées", "Gantées"], 1, "SHA inefficace sur des mains humides ou souillées."],
        ["4", "En présence de souillures visibles (sang, selles) :", ["Friction SHA suffit", "Lavage à l'eau et savon obligatoire", "Rien à faire", "Utiliser du gel désinfectant"], 1],
        ["5", "Le port de bijoux au poignet :", ["Est autorisé", "Est interdit lors des soins", "N'a aucun impact", "Est recommandé"], 1, "Alliance lisse tolérée dans certaines structures, tout autre bijou interdit."],
        ["6", "Les précautions standard incluent notamment :", ["Hygiène des mains, EPI, gestion excrétas, AES", "Uniquement le port de gants", "Uniquement la SHA", "Isolement du patient"], 0],
        ["7", "Un masque chirurgical protège surtout :", ["Le soignant contre les aérosols", "L'entourage des projections du porteur", "Contre les UV", "Contre les gaz toxiques"], 1],
        ["8", "L'appareil de protection respiratoire FFP2 protège :", ["L'entourage", "Le porteur contre les aérosols infectieux", "Contre les liquides uniquement", "Contre les odeurs"], 1],
        ["9", "Les gants à usage unique doivent être changés :", ["1x par jour", "Entre chaque patient et entre 2 soins", "Uniquement s'ils sont troués", "Jamais si mains propres"], 1],
        ["10", "L'ordre correct d'habillage :", ["Gants, masque, tablier", "Hygiène des mains, tablier, masque, lunettes, gants", "Gants puis masque puis SHA", "Masque puis gants puis tablier"], 1],
      ]),
    },
    {
      id: "dea-hyg-2",
      title: "Nettoyage & désinfection du VSL/ASSU",
      emoji: "🚑",
      questions: mk("dea-hygiene", "dea-hyg-2", [
        ["1", "Un bio-nettoyage classique du véhicule se fait :", ["Une fois par semaine", "Après chaque transport", "Une fois par mois", "Uniquement en fin de garde"], 1],
        ["2", "Un détergent-désinfectant permet :", ["Uniquement de nettoyer", "Nettoyer et désinfecter en une étape", "Uniquement de désinfecter", "De stériliser"], 1],
        ["3", "La désinfection terminale (patient contagieux) utilise :", ["De l'eau claire", "Un détergent-désinfectant + temps de contact respecté", "De l'eau de Javel pure", "Un chiffon sec"], 1],
        ["4", "Le sens du nettoyage va :", ["Du sale vers le propre", "Du propre vers le sale", "Peu importe", "En cercles"], 1, "Toujours du plus propre vers le plus sale."],
        ["5", "Après un transport suspect COVID / tuberculose :", ["Nettoyage standard", "Aération + désinfection renforcée", "Aucune procédure spécifique", "Uniquement changer les draps"], 1],
        ["6", "Le temps de contact d'un désinfectant :", ["N'a pas d'importance", "Doit être respecté selon la notice", "Est toujours de 10 s", "Est toujours de 1 h"], 1],
        ["7", "Le brancard est désinfecté :", ["1x par semaine", "Après chaque patient", "1x par mois", "Uniquement s'il est visiblement sale"], 1],
        ["8", "Les draps à usage unique :", ["Se réutilisent 1x", "Se jettent après chaque patient", "Se lavent en machine", "Ne s'utilisent que la nuit"], 1],
        ["9", "La tenue professionnelle :", ["Se porte à la maison", "Est changée quotidiennement au minimum", "Se change 1x par semaine", "Ne se lave pas"], 1],
        ["10", "L'aération de la cellule sanitaire :", ["Est inutile", "Doit être systématique entre 2 transports", "Se fait 1x par jour", "N'est faite qu'en été"], 1],
      ]),
    },
    {
      id: "dea-hyg-3",
      title: "DASRI & risque infectieux",
      emoji: "🗑️",
      questions: mk("dea-hygiene", "dea-hyg-3", [
        ["1", "DASRI signifie :", ["Déchets Ambulanciers Standards", "Déchets d'Activités de Soins à Risques Infectieux", "Déchets Assimilables aux Résidus Industriels", "Documents d'Aide au Soin"], 1],
        ["2", "Une aiguille souillée se jette dans :", ["Poubelle noire", "Sac DASRI jaune", "Collecteur OPCT rigide", "Sac ménager"], 2, "Objets Piquants/Coupants/Tranchants → collecteur rigide dédié."],
        ["3", "Un pansement souillé de sang va dans :", ["Sac noir", "Sac DASRI jaune", "Toilettes", "Container OPCT"], 1],
        ["4", "Le collecteur OPCT ne doit jamais :", ["Être en position verticale", "Dépasser la limite de remplissage", "Être fermé", "Être identifié"], 1],
        ["5", "Un AES est :", ["Accident d'exposition au sang", "Accident électrique", "Alerte d'évacuation", "Aération d'urgence"], 0],
        ["6", "Après piqûre avec aiguille souillée, il faut d'abord :", ["Faire saigner et laver à l'eau et savon", "Aspirer la plaie", "Mettre un pansement sec", "Attendre la consultation"], 0, "Ne pas faire saigner en pressant, laisser saigner ; laver 5 min ; antiseptique."],
        ["7", "Le sérodiagnostic après AES :", ["N'est pas nécessaire", "Doit être proposé rapidement (consultation dédiée)", "Se fait 1 an après", "Est facultatif"], 1],
        ["8", "Recapuchonner une aiguille est :", ["Recommandé", "Formellement interdit", "Obligatoire", "Utile pour ranger"], 1],
        ["9", "Le sac DASRI est :", ["Noir", "Jaune", "Vert", "Bleu"], 1],
        ["10", "Les DASRI doivent être éliminés dans un délai maximal de :", ["24 heures", "72 heures", "7 jours (production >5kg/mois)", "1 mois"], 2, "Décret 97-1048 : 72 h si >5 kg/mois, sinon jusqu'à 3 mois ou 7 j selon volume."],
      ]),
    },
  ],
};

// ============================================================
// UNITÉ 2 — SÉCURITÉ, EPI, ABORD DE LA VICTIME
// ============================================================
const SECU: Unit = {
  id: "dea-secu",
  title: "Sécurité & abord victime",
  subtitle: "Protéger avant tout",
  color: "warning",
  icon: "🦺",
  lessons: [
    {
      id: "dea-sec-1",
      title: "Sécurité de l'intervention",
      emoji: "⚠️",
      questions: mk("dea-secu", "dea-sec-1", [
        ["1", "L'ordre des priorités sur intervention est :", ["Moi, l'équipe, la victime, les témoins", "Victime, moi, témoins", "Témoins, victime, moi", "Peu importe"], 0, "Se protéger d'abord, puis protéger, puis secourir."],
        ["2", "Sur un accident de la voie publique, on positionne le véhicule :", ["Devant la scène", "En protection, feux allumés, avant la scène dans le sens du trafic", "En travers de la route", "N'importe où"], 1],
        ["3", "En cas de fuite de carburant :", ["Fumer", "Interdire de fumer, éloigner et sécuriser", "S'approcher", "Utiliser un briquet pour voir"], 1],
        ["4", "Les feux de détresse s'allument :", ["Jamais", "À l'arrêt sur intervention et lors de risque", "Uniquement la nuit", "Uniquement en ville"], 1],
        ["5", "En intérieur (fumées, gaz), on doit :", ["Entrer sans matériel", "Attendre les pompiers si risque, extraire dès que possible en sécurité", "Ouvrir toutes les portes", "Fumer une cigarette"], 1],
        ["6", "L'EPI de base en intervention comprend :", ["Chaussures de ville", "Chaussures de sécurité, tenue haute visibilité", "Uniquement des gants", "Un casque de moto"], 1],
        ["7", "Sur voie rapide, la mise en sécurité passe par :", ["Marcher au milieu de la voie", "Se positionner derrière les glissières et porter la HV", "Rester devant le véhicule", "Éteindre les feux"], 1],
        ["8", "Face à un individu agressif, on doit :", ["Le maîtriser", "Se mettre à distance, appeler les forces de l'ordre", "L'ignorer", "Contre-attaquer"], 1],
        ["9", "Le balisage minimum en amont d'un accident :", ["10 m", "30 m en ville, 150-200 m sur route rapide", "5 m", "500 m partout"], 1],
        ["10", "Un chien agressif dans une intervention :", ["S'écarter, demander au propriétaire ou aux forces de l'ordre", "Le caresser", "Le frapper", "Continuer sans en tenir compte"], 0],
      ]),
    },
    {
      id: "dea-sec-2",
      title: "Approche de la victime & communication",
      emoji: "🗣️",
      questions: mk("dea-secu", "dea-sec-2", [
        ["1", "L'abord d'un patient commence par :", ["Le soulever", "Se présenter, se mettre à sa hauteur, expliquer", "Le déshabiller", "Prendre la tension"], 1],
        ["2", "Le secret professionnel :", ["Ne s'applique pas au DEA", "S'applique à tous les professionnels de santé, y compris ambulanciers", "S'applique uniquement au médecin", "Est facultatif"], 1],
        ["3", "Une information au patient doit être :", ["Compliquée pour rassurer", "Claire, adaptée, loyale", "Fausse si nécessaire", "Absente"], 1],
        ["4", "Le consentement du patient :", ["N'est pas obligatoire", "Doit être recherché sauf urgence vitale immédiate", "Est valable uniquement écrit", "N'existe pas pour les majeurs"], 1],
        ["5", "Une personne mineure nécessite :", ["Aucun accord", "L'accord des titulaires de l'autorité parentale (sauf urgence vitale)", "L'accord du maire", "L'accord de la CPAM"], 1],
        ["6", "Face à un refus de soin d'un patient conscient et lucide :", ["On oblige", "On respecte, on informe, on trace, on prévient la régulation", "On appelle les forces de l'ordre systématiquement", "On part immédiatement sans rien dire"], 1],
        ["7", "L'échelle EVN de la douleur va de :", ["0 à 5", "0 à 10", "0 à 100", "1 à 4"], 1],
        ["8", "La distance de communication adéquate est :", ["4 m", "Environ 1 m, face à face", "10 cm", "Dans le dos"], 1],
        ["9", "Face à une personne sourde :", ["Crier", "Se placer face, articuler, écrire au besoin", "Ignorer", "Parler à ses proches uniquement"], 1],
        ["10", "L'écoute active c'est :", ["Couper la parole", "Reformuler, laisser parler, observer le non-verbal", "Parler beaucoup", "Prendre des notes uniquement"], 1],
      ]),
    },
  ],
};

// ============================================================
// UNITÉ 3 — BILANS
// ============================================================
const BILANS: Unit = {
  id: "dea-bilans",
  title: "Les bilans",
  subtitle: "Circonstanciel, primaire, secondaire",
  color: "primary",
  icon: "📋",
  lessons: [
    {
      id: "dea-bil-1",
      title: "Bilan circonstanciel",
      emoji: "🧭",
      questions: mk("dea-bilans", "dea-bil-1", [
        ["1", "Le bilan circonstanciel évalue :", ["L'état clinique", "L'environnement, les risques, le nombre de victimes", "Les paramètres vitaux", "Les antécédents"], 1],
        ["2", "Il se réalise :", ["Après tous les soins", "En arrivant sur les lieux, avant l'approche", "À l'hôpital", "En fin d'intervention"], 1],
        ["3", "Il permet notamment de :", ["Prendre la TA", "Demander des moyens supplémentaires si besoin", "Faire une glycémie", "Débuter une RCP"], 1],
        ["4", "Si plusieurs victimes, on transmet :", ["Rien", "Nombre, gravité approximative, moyens nécessaires", "Uniquement le nom", "Le numéro de sécurité sociale"], 1],
        ["5", "Un cinétique violente (chute > 3 m, éjection) doit :", ["Être négligée", "Faire suspecter un polytraumatisme", "Rassurer", "Ne pas être transmise"], 1],
        ["6", "Le bilan circonstanciel se transmet à :", ["Personne", "La régulation (SAMU/coordination)", "Uniquement à la famille", "Uniquement à l'hôpital"], 1],
        ["7", "Face à un accident électrique :", ["Toucher la victime tout de suite", "Couper le courant avant tout contact", "Verser de l'eau", "Utiliser une pince métallique"], 1],
        ["8", "Face à un incendie :", ["Entrer sans EPI", "Attendre les pompiers, prendre en charge à distance", "Éteindre soi-même", "Fumer pour se calmer"], 1],
        ["9", "Face à un accident avec victimes multiples, on transmet en priorité :", ["Le nom des victimes", "Le nombre, la gravité, les moyens à renforcer", "Le prix du matériel", "Les antécédents"], 1],
        ["10", "En cas de risque persistant, la victime est prise en charge :", ["Sur place", "Après mise en sécurité", "Jamais", "Uniquement par le médecin"], 1],
      ]),
    },
    {
      id: "dea-bil-2",
      title: "Bilan primaire (vital) — ABCDE",
      emoji: "🚨",
      questions: mk("dea-bilans", "dea-bil-2", [
        ["1", "L'ordre du bilan vital est :", ["ABCDE", "EDCBA", "ABDCE", "BADCE"], 0, "Airway - Breathing - Circulation - Disability - Exposure."],
        ["2", "« A » désigne :", ["Alerte", "Airway = liberté des voies aériennes", "Analgésie", "Aorte"], 1],
        ["3", "« B » désigne :", ["Breathing = ventilation", "Bras", "Blessure", "Bassin"], 0],
        ["4", "« C » désigne :", ["Coma", "Circulation", "Colonne", "Carotide"], 1],
        ["5", "« D » désigne :", ["Diagnostic", "Disability = conscience, neurologique", "Douleur", "Dyspnée"], 1],
        ["6", "« E » désigne :", ["Épaule", "Exposure = examen complet et environnement", "Écoulement", "Épistaxis"], 1],
        ["7", "Une fréquence respiratoire adulte normale se situe :", ["6-10/min", "12-20/min", "25-35/min", "40-50/min"], 1],
        ["8", "Une FC adulte normale se situe :", ["30-50 bpm", "60-100 bpm", "110-140 bpm", "150-200 bpm"], 1],
        ["9", "Une SpO₂ normale (adulte sain) :", ["70-80 %", "≥ 95 %", "50-60 %", "100 % obligatoire"], 1],
        ["10", "Une TAS adulte normale :", ["50-70 mmHg", "environ 100-140 mmHg", "180-200 mmHg", "< 50 mmHg"], 1],
        ["11", "La liberté des voies aériennes se vérifie par :", ["Auscultation cardiaque", "Voir, écouter, sentir + observation buccale", "Prise de TA", "Glycémie"], 1],
        ["12", "Une détresse respiratoire chez l'adulte se traduit par :", ["FR normale", "FR > 25 ou < 10, tirage, cyanose, sueurs", "FC lente", "Douleur au genou"], 1],
        ["13", "Une détresse circulatoire se traduit notamment par :", ["Bradycardie et hypertension", "Tachycardie, hypotension, marbrures, TRC > 3 s", "Fièvre isolée", "Vomissement isolé"], 1],
        ["14", "Le TRC (temps de recoloration cutanée) normal :", ["> 5 s", "< 3 s", "> 10 s", "N'existe pas"], 1],
        ["15", "L'échelle AVPU évalue :", ["La douleur", "La conscience (Alerte, Voix, Pain, Unresponsive)", "La respiration", "La TA"], 1],
      ]),
    },
    {
      id: "dea-bil-3",
      title: "Bilan secondaire & paramètres",
      emoji: "🩺",
      questions: mk("dea-bilans", "dea-bil-3", [
        ["1", "Le bilan secondaire se fait :", ["Avant le bilan vital", "Après avoir écarté les détresses vitales", "En dernier à l'hôpital", "Jamais"], 1],
        ["2", "SAMPLE signifie :", ["Signes/Symptômes, Allergies, Médicaments, Passé, Last meal, Événement", "Système Ambulancier Modernisé Pratique et Léger", "Bilan uniquement circulatoire", "Rien de médical"], 0],
        ["3", "La glycémie capillaire normale à jeun :", ["0,4-0,6 g/L", "0,7-1,10 g/L", "1,5-2 g/L", "3-4 g/L"], 1],
        ["4", "Une hypoglycémie se définit par :", ["< 0,6 g/L (3,3 mmol/L) avec signes", "> 2 g/L", "> 3 g/L", "> 5 g/L"], 0],
        ["5", "L'échelle de Glasgow va de :", ["1 à 10", "3 à 15", "0 à 20", "5 à 25"], 1],
        ["6", "Un score de Glasgow à 8 correspond à :", ["Conscience normale", "Coma / seuil d'intubation", "État agité", "Sommeil profond physiologique"], 1],
        ["7", "L'échelle de Glasgow évalue :", ["Ouverture des yeux, réponse verbale, réponse motrice", "Douleur uniquement", "Respiration uniquement", "Force musculaire uniquement"], 0],
        ["8", "La température normale centrale :", ["32-34 °C", "36-37,5 °C", "38-39 °C", "39-40 °C"], 1],
        ["9", "Une hypothermie légère :", ["> 40 °C", "32-35 °C", "35-36 °C", "20-25 °C"], 1],
        ["10", "L'oxymétrie de pouls mesure :", ["La glycémie", "La saturation en O₂ et la FC", "La TA", "La température"], 1],
        ["11", "Une SpO₂ à 88 % signifie :", ["Normale", "Hypoxémie, nécessite de l'oxygène", "Hyperoxie", "Panne du capteur systématique"], 1],
        ["12", "La pression artérielle moyenne (PAM) approximative :", ["PAS × 2", "(PAS + 2×PAD) / 3", "PAS - PAD", "(PAS+PAD)/2"], 1],
        ["13", "Une PAM insuffisante pour la perfusion des organes :", ["< 65 mmHg", "> 120 mmHg", "= 100 mmHg", "> 200 mmHg"], 0],
        ["14", "Une FR à 8/min adulte :", ["Est normale", "Est une bradypnée à surveiller / à ventiler si signes", "Est une tachypnée", "N'a aucun intérêt"], 1],
        ["15", "Le pouls filant traduit :", ["Une bonne santé", "Un état de choc débutant", "Une hypertension", "Rien"], 1],
      ]),
    },
    {
      id: "dea-bil-4",
      title: "Transmission & LATA",
      emoji: "📞",
      questions: mk("dea-bilans", "dea-bil-4", [
        ["1", "Une transmission au SAMU commence par :", ["Le prénom de l'ambulancier uniquement", "L'identification de l'équipe et le lieu", "La météo", "La religion du patient"], 1],
        ["2", "Une transmission SAMPLE comprend l'événement, mais aussi :", ["Signes, allergies, ttt, ATCD, dernier repas", "Uniquement le nom", "Uniquement la TA", "Uniquement la SpO₂"], 0],
        ["3", "Le radio-message doit être :", ["Long et détaillé", "Court, structuré, clair (SBAR ou équivalent)", "En verlan", "En anglais"], 1],
        ["4", "SBAR signifie :", ["Situation, Background, Assessment, Recommendation", "Système Belge d'Alerte Rapide", "Sécurité Bilan Alerte Rapport", "Rien"], 0],
        ["5", "Le dossier patient doit être :", ["Sur post-it", "Tracé (paramètres, gestes, horaires, personnes)", "Oral uniquement", "Facultatif"], 1],
        ["6", "Une LATA est :", ["Une limitation ou arrêt des thérapeutiques actives", "Une pathologie", "Un médicament", "Un score"], 0],
        ["7", "Face à une directive anticipée écrite refusant la réanimation :", ["On ignore", "On respecte, on trace, on transmet à la régulation", "On force la RCP", "On appelle la police"], 1],
        ["8", "La personne de confiance :", ["Est le premier voisin", "Est désignée par écrit par le patient", "Est le médecin traitant obligatoirement", "N'existe pas"], 1],
        ["9", "Un mineur nécessite :", ["Aucun bilan", "Une information à ses parents et une prise en charge adaptée", "Aucun consentement", "L'accord de l'école"], 1],
        ["10", "L'horodatage des paramètres :", ["Est facultatif", "Est indispensable (traçabilité, évolution)", "Se fait à la fin uniquement", "Se fait uniquement par le médecin"], 1],
      ]),
    },
  ],
};

// ============================================================
// UNITÉ 4 — DÉTRESSES VITALES
// ============================================================
const DETRESSES: Unit = {
  id: "dea-detresses",
  title: "Détresses vitales",
  subtitle: "Respi, circu, neuro",
  color: "destructive",
  icon: "🚑",
  lessons: [
    {
      id: "dea-det-1",
      title: "Détresse respiratoire",
      emoji: "🫁",
      questions: mk("dea-detresses", "dea-det-1", [
        ["1", "Un signe de détresse respiratoire est :", ["Bradypnée régulière", "Tirage, balancement, sueurs, cyanose", "Fièvre modérée seule", "Douleur au bras seule"], 1],
        ["2", "La cyanose apparaît quand la SpO₂ est autour de :", ["> 95 %", "< 85 %", "= 100 %", "= 92 %"], 1],
        ["3", "Un patient dyspnéique conscient est mis en position :", ["Décubitus dorsal strict", "Demi-assise", "Trendelenburg", "PLS systématique"], 1],
        ["4", "Devant une dyspnée avec SpO₂ à 88 % :", ["Rien à faire", "Oxygénothérapie adaptée + bilan", "Retirer le pouls", "Refuser le transport"], 1],
        ["5", "L'oxygène au masque haute concentration délivre environ :", ["21 %", "24-28 %", "40 %", "80-100 % à 12-15 L/min"], 3],
        ["6", "L'oxygène aux lunettes délivre environ :", ["1 L/min → ~24 %, 4 L/min → ~36 %", "12 L/min → 100 %", "0 %", "50 %"], 0],
        ["7", "Une obstruction totale des voies aériennes chez l'adulte conscient impose :", ["Rassurer", "Claques dans le dos puis compressions abdominales (Heimlich)", "Boire de l'eau", "Ne rien faire"], 1],
        ["8", "Une obstruction partielle (toux efficace) :", ["Manœuvre de Heimlich immédiate", "Encourager la toux, surveiller", "Faire boire", "Endormir"], 1],
        ["9", "Chez le nourrisson conscient qui s'étouffe :", ["Heimlich abdominal", "5 tapes dorsales + 5 compressions thoraciques", "Boire un biberon", "Rien"], 1],
        ["10", "Un asthme aigu grave se caractérise par :", ["Sifflements + parole complète", "Silence auscultatoire, épuisement, cyanose", "Absence de dyspnée", "TA élevée isolée"], 1],
        ["11", "Un OAP (œdème aigu du poumon) donne classiquement :", ["Toux sèche isolée", "Dyspnée + crépitants bilatéraux + orthopnée", "Fièvre isolée", "Douleur abdominale isolée"], 1],
        ["12", "Face à un OAP conscient :", ["Position allongée", "Position demi-assise, O₂, appel régulation", "Trendelenburg", "PLS"], 1],
        ["13", "Une bradypnée < 10/min chez l'adulte impose :", ["Rien", "Surveillance étroite, O₂, préparation à assister la ventilation", "Course à pied", "Compression thoracique"], 1],
        ["14", "Une pause respiratoire = ", ["Apnée", "Tachypnée", "Eupnée", "Hyperpnée"], 0],
        ["15", "L'insufflation au BAVU se fait :", ["En 3 s puissantes", "En 1 s, volume adapté, sans surinsuffler", "Aussi fort que possible", "Uniquement bouche à bouche"], 1],
      ]),
    },
    {
      id: "dea-det-2",
      title: "Détresse circulatoire & états de choc",
      emoji: "💔",
      questions: mk("dea-detresses", "dea-det-2", [
        ["1", "Un état de choc est :", ["Une peur", "Une insuffisance circulatoire aiguë avec hypoperfusion tissulaire", "Une TA élevée", "Un stress passager"], 1],
        ["2", "Signes cliniques du choc :", ["Bradycardie et hypertension", "Pâleur, marbrures, sueurs, tachycardie, hypoTA, TRC>3s", "Rougeur, chaleur, sourire", "Rien de spécifique"], 1],
        ["3", "Le choc hypovolémique est dû à :", ["Une infection", "Une perte de volume (hémorragie, brûlures, déshydratation)", "Une allergie", "Un problème cardiaque isolé"], 1],
        ["4", "Le choc cardiogénique est dû à :", ["Défaillance de la pompe cardiaque", "Une hémorragie", "Une infection", "Une allergie"], 0],
        ["5", "Le choc septique est dû à :", ["Un cœur défaillant", "Une infection généralisée", "Une hémorragie", "Une réaction allergique"], 1],
        ["6", "Le choc anaphylactique est dû à :", ["Une allergie sévère", "Un infarctus", "Une hémorragie", "Un stress"], 0],
        ["7", "Un pouls filant + PAS < 90 chez l'adulte suggère :", ["État normal", "État de choc", "Fièvre", "Constipation"], 1],
        ["8", "Devant un choc hypovolémique, la position recommandée est :", ["Debout", "Allongée, jambes surélevées (si possible), au chaud", "Assise", "Sur le ventre"], 1],
        ["9", "Une hémorragie extériorisée massive impose en premier :", ["Prendre la TA", "Compression manuelle directe puis pansement compressif", "Boire", "Rien"], 1],
        ["10", "Si la compression directe est impossible ou inefficace sur un membre :", ["Attendre", "Garrot tactique posé et horodaté", "Massage cardiaque", "Antalgique"], 1],
        ["11", "Le garrot se pose :", ["Sur une articulation", "En amont de la plaie, sur un segment de membre, serré jusqu'à arrêt du saignement", "N'importe où", "Sur la plaie directement"], 1],
        ["12", "Un patient en choc doit être :", ["Refroidi", "Réchauffé (couverture de survie côté argenté vers le corps par froid)", "Aspergé d'eau", "Laissé nu"], 1],
        ["13", "Le score de choc (indice de Allgöwer) :", ["FC/PAS ; > 1 = choc probable", "PAS/FC", "FR/PAS", "Glycémie/2"], 0],
        ["14", "Une douleur thoracique constrictive chez un adulte doit faire évoquer :", ["Un rhume", "Un syndrome coronarien aigu", "Une entorse", "Une carie"], 1],
        ["15", "Face à une douleur thoracique évocatrice d'IDM :", ["Faire marcher le patient", "Repos strict, O₂ si SpO₂<94 %, appel 15, préparation transport", "Faire du sport", "Antalgique et retour maison"], 1],
      ]),
    },
    {
      id: "dea-det-3",
      title: "Détresse neurologique",
      emoji: "🧠",
      questions: mk("dea-detresses", "dea-det-3", [
        ["1", "L'AVC ischémique est :", ["Une rupture vasculaire", "Une occlusion vasculaire cérébrale", "Une méningite", "Un traumatisme"], 1],
        ["2", "L'AVC hémorragique est :", ["Une occlusion", "Une rupture vasculaire cérébrale", "Une infection", "Un caillot pulmonaire"], 1],
        ["3", "Le FAST évalue :", ["Face, Arm, Speech, Time", "Fièvre, Anémie, Sang, Toux", "Rien", "Une échelle de douleur"], 0],
        ["4", "Devant un AVC suspecté, la conduite est :", ["Aspirine", "Alerte 15, transport rapide vers UNV, position adaptée", "Faire boire du sucre", "Attendre 24 h"], 1],
        ["5", "L'heure de début des symptômes d'AVC est :", ["Sans importance", "Cruciale (fenêtre de thrombolyse)", "Notée à titre indicatif", "Confidentielle"], 1],
        ["6", "Une hémiplégie touche :", ["Les 2 côtés", "Un côté du corps", "Uniquement le visage", "Uniquement les jambes"], 1],
        ["7", "Une aphasie est :", ["Un trouble du langage", "Une paralysie faciale", "Une douleur", "Une cécité"], 0],
        ["8", "Une crise convulsive tonico-clonique impose de :", ["Mettre un objet en bouche", "Sécuriser l'environnement, ne rien introduire en bouche, PLS après", "Retenir les mouvements", "Gifler"], 1],
        ["9", "La phase post-critique se caractérise par :", ["Reprise de conscience immédiate", "Confusion, somnolence, amnésie", "Douleur thoracique", "Fièvre systématique"], 1],
        ["10", "Une crise de plus de 5 minutes est :", ["Bénigne", "Un état de mal épileptique → urgence, appel 15", "Un rêve", "Une syncope"], 1],
        ["11", "Un score de Glasgow ≤ 8 :", ["Est normal", "Impose une prise en charge intensive (protection VA)", "N'a pas d'importance", "Ne se calcule pas"], 1],
        ["12", "Une hypoglycémie peut mimer :", ["Un rhume", "Un AVC ou une confusion aiguë", "Une entorse", "Une carie"], 1],
        ["13", "Face à un patient inconscient qui respire normalement :", ["Massage cardiaque", "PLS + surveillance + O₂ si besoin + bilan", "Laisser sur le dos", "Faire boire"], 1],
        ["14", "Le score de Glasgow à 3 correspond à :", ["Conscient orienté", "Coma le plus profond (aucune réponse)", "Somnolence", "Absence de score"], 1],
        ["15", "Une méningite peut se traduire par :", ["Céphalée, fièvre, raideur de nuque, photophobie", "Ronflements uniquement", "Ptose isolée", "Diarrhée isolée"], 0],
      ]),
    },
  ],
};

// ============================================================
// UNITÉ 5 — GESTES D'URGENCE
// ============================================================
const GESTES: Unit = {
  id: "dea-gestes",
  title: "Gestes d'urgence",
  subtitle: "RCP, DAE, PLS, hémorragies",
  color: "destructive",
  icon: "🫀",
  lessons: [
    {
      id: "dea-ges-1",
      title: "Position latérale de sécurité (PLS)",
      emoji: "🛌",
      questions: mk("dea-gestes", "dea-ges-1", [
        ["1", "La PLS s'adresse à :", ["Patient conscient orienté", "Patient inconscient qui respire", "Arrêt cardiaque", "Fracture ouverte du fémur isolée"], 1],
        ["2", "L'objectif principal de la PLS est :", ["Le confort", "Maintenir la liberté des voies aériennes", "Faire dormir", "Traiter la douleur"], 1],
        ["3", "Chez la femme enceinte inconnue > 6 mois, la PLS est faite :", ["À droite", "Sur le côté gauche", "Peu importe", "Sur le dos"], 1, "Décubitus latéral gauche pour éviter la compression cave."],
        ["4", "Avant la PLS, il faut :", ["Vérifier la respiration", "Vérifier conscience et respiration", "Faire un massage", "Prendre la TA uniquement"], 1],
        ["5", "En PLS, la tête doit être :", ["Droite", "En légère extension, bouche vers le bas", "En flexion forcée", "Sur un oreiller mou"], 1],
        ["6", "La PLS est contre-indiquée si :", ["Suspicion de traumatisme rachidien SANS détresse VAS", "Toujours", "Chez l'enfant", "Chez la personne âgée"], 0],
        ["7", "Fréquence de réévaluation de la respiration en PLS :", ["1x/heure", "Toutes les 1-2 min ou en continu", "Jamais", "1x/jour"], 1],
        ["8", "Si le patient recommence à respirer normalement après RCP :", ["Continuer les compressions", "PLS + surveillance + O₂", "Le lever", "Retirer le DAE"], 1],
        ["9", "En PLS, le membre supérieur du côté du sol :", ["Est glissé sous le corps", "Est plié à 90° vers l'avant", "Est cassé", "Peu importe"], 1],
        ["10", "En PLS, la jambe du dessus est :", ["Étirée", "Fléchie à angle droit pour stabiliser", "Sous la personne", "Attachée"], 1],
      ]),
    },
    {
      id: "dea-ges-2",
      title: "Arrêt cardio-respiratoire & RCP",
      emoji: "❤️‍🩹",
      questions: mk("dea-gestes", "dea-ges-2", [
        ["1", "L'ACR se diagnostique sur :", ["Absence de conscience + absence/gasps respiration", "Douleur thoracique", "Fièvre", "Marbrures isolées"], 0],
        ["2", "Face à un ACR adulte, on débute :", ["30 insufflations puis 2 compressions", "30 compressions puis 2 insufflations", "Uniquement des insufflations", "Attendre le SMUR"], 1],
        ["3", "Fréquence des compressions thoraciques adulte :", ["60-80/min", "100-120/min", "150-180/min", "30/min"], 1],
        ["4", "Profondeur des compressions adulte :", ["1 cm", "5-6 cm", "10-12 cm", "0,5 cm"], 1],
        ["5", "Emplacement des compressions adulte :", ["Milieu de l'abdomen", "Milieu du sternum, moitié inférieure", "Sur la clavicule", "Sur le rachis"], 1],
        ["6", "Ratio adulte compressions/insufflations sans intubation :", ["15/2", "30/2", "5/1", "50/2"], 1],
        ["7", "Ratio enfant à 2 sauveteurs professionnels :", ["30/2", "15/2", "5/1", "50/1"], 1],
        ["8", "Chez le nourrisson, les compressions se font avec :", ["Une main", "Deux pouces encerclant le thorax (2 sauveteurs) ou 2 doigts", "Le poing", "Le coude"], 1],
        ["9", "Profondeur des compressions chez l'enfant :", ["1 cm", "Environ 1/3 du diamètre AP du thorax (~5 cm)", "10 cm", "0 cm"], 1],
        ["10", "Le relais compressions se fait au minimum toutes les :", ["10 s", "2 minutes", "10 minutes", "30 minutes"], 1, "Pour éviter la baisse d'efficacité."],
        ["11", "La reprise entre compressions doit permettre :", ["Un décollement complet du thorax", "Une pression permanente", "Un pincement", "Un frottement"], 0],
        ["12", "Une pause pour DAE doit être :", ["Aussi courte que possible", "De 5 min", "De 10 min", "Aucune importance"], 0],
        ["13", "Une RCP se poursuit :", ["Jusqu'à la fatigue", "Jusqu'à reprise d'activité, relais médicalisé, ou décision d'arrêt", "1 min", "5 min"], 1],
        ["14", "L'insufflation au BAVU se fait :", ["Sur 3 s à pleine amplitude", "Sur ~1 s, volume normal, jusqu'à soulèvement thoracique visible", "En force maximale", "Bouche à bouche uniquement"], 1],
        ["15", "En cas de doute sur un gasp isolé, on doit :", ["Considérer comme respiration normale", "Considérer comme absence de respiration → RCP", "Attendre 5 min", "Rassurer"], 1],
      ]),
    },
    {
      id: "dea-ges-3",
      title: "Défibrillateur (DAE)",
      emoji: "⚡",
      questions: mk("dea-gestes", "dea-ges-3", [
        ["1", "Le DAE analyse :", ["La TA", "Le rythme cardiaque", "La glycémie", "La SpO₂"], 1],
        ["2", "Les électrodes se posent :", ["Sur les 2 pectoraux", "Sous la clavicule droite et sous l'aisselle gauche", "Sur le dos uniquement", "Sur le ventre"], 1],
        ["3", "Pendant l'analyse :", ["Continuer le massage", "Ne toucher personne, personne ne touche le patient", "Serrer le patient", "Bouger la victime"], 1],
        ["4", "Un choc est indiqué en cas de :", ["Asystolie", "Fibrillation ventriculaire ou TV sans pouls", "Sinusal normal", "Bloc"], 1],
        ["5", "Après un choc :", ["Attendre le pouls 1 min", "Reprendre immédiatement 2 min de RCP", "Retirer le DAE", "Vérifier la TA"], 1],
        ["6", "Le DAE peut s'utiliser chez l'enfant > 1 an :", ["Non", "Oui, avec électrodes/mode pédiatriques si dispo, sinon adulte", "Uniquement adulte", "Interdit"], 1],
        ["7", "Sur un torse mouillé :", ["Choquer directement", "Sécher rapidement avant de coller les électrodes", "Rincer à l'eau", "Attendre"], 1],
        ["8", "Sur un torse très pileux :", ["Peu importe", "Raser rapidement si mauvais contact", "Peindre", "Coller sur les poils"], 1],
        ["9", "Un patient porteur de pacemaker :", ["Contre-indique le DAE", "Autorise le DAE, éviter de coller sur le boîtier", "Doit être retourné", "Ne se voit pas au toucher"], 1],
        ["10", "Un patient avec patch médicamenteux :", ["Coller par-dessus", "Retirer le patch avant collage des électrodes", "Aucune action", "Interdire le DAE"], 1],
        ["11", "Sur environnement humide (piscine) :", ["Choquer dans l'eau", "Extraire de l'eau, sécher et choquer sur surface sèche", "Interdit", "Retirer les vêtements uniquement"], 1],
        ["12", "Le DAE peut délivrer :", ["Un choc à la place du RCP", "Uniquement un choc si rythme choquable", "Un anesthésiant", "De l'O₂"], 1],
        ["13", "Après reprise d'activité cardiaque spontanée :", ["Retirer immédiatement électrodes", "Laisser électrodes en place, surveillance", "Faire marcher le patient", "Retirer O₂"], 1],
        ["14", "L'objectif de la défibrillation précoce :", ["Réanimer sans RCP", "Augmenter significativement la survie de la FV", "Baisser la TA", "Baisser la glycémie"], 1],
        ["15", "Un DAE doit être vérifié :", ["Jamais", "Selon la notice (autotests, dates piles/électrodes)", "1 fois par an uniquement", "Uniquement en cas d'intervention"], 1],
      ]),
    },
    {
      id: "dea-ges-4",
      title: "Hémorragies & garrot",
      emoji: "🩸",
      questions: mk("dea-gestes", "dea-ges-4", [
        ["1", "Une hémorragie extériorisée abondante nécessite :", ["Pansement sec léger", "Compression manuelle directe immédiate", "Rien", "Trendelenburg seul"], 1],
        ["2", "Si compression insuffisante ou impossible sur un membre :", ["Attendre", "Pose d'un garrot en amont", "Massage", "Membre en l'air"], 1],
        ["3", "Un garrot posé doit :", ["Être desserré chaque 5 min", "Rester en place jusqu'à prise en charge médicale, être horodaté", "Être caché sous les vêtements", "Être retiré si le patient se plaint"], 1],
        ["4", "Un garrot mal serré peut :", ["Améliorer le débit", "Aggraver le saignement (stase veineuse)", "Rien", "Faire baisser la TA"], 1],
        ["5", "Sur une hémorragie du cou :", ["Garrot", "Compression manuelle prudente sans obstruer VA", "Sécher", "Rien"], 1],
        ["6", "Une épistaxis se traite par :", ["Tête en arrière", "Tête penchée en avant + compression narinaire 10 min", "Boire de l'eau", "Se moucher fort"], 1],
        ["7", "Une hémorragie interne se suspecte devant :", ["Pâleur, sueurs, tachycardie, hypoTA + contexte traumatique", "Fièvre isolée", "Éruption cutanée", "Ronflement"], 0],
        ["8", "Une plaie soufflante thoracique se recouvre :", ["D'un pansement occlusif étanche 4 côtés", "D'un pansement 3 côtés (valve unidirectionnelle)", "De rien", "D'un garrot"], 1],
        ["9", "Un corps étranger empalé :", ["Se retire", "Se laisse en place, s'immobilise, transport rapide", "Se casse", "S'ignore"], 1],
        ["10", "En cas d'amputation :", ["Le segment est jeté", "Segment enveloppé, conservé au frais (pas contact direct glace)", "Segment enterré", "Segment lavé au savon"], 1],
        ["11", "Un pansement compressif efficace :", ["Coule de sang à travers", "Arrête le saignement, TRC en aval maintenu si possible", "Trop lâche", "En papier"], 1],
        ["12", "Une hémorragie externe s'objective par :", ["Un simple frottis", "Un saignement continu qui imbibe compresses/vêtements", "Une rougeur simple", "Une chaleur locale"], 1],
        ["13", "Après pose d'un garrot :", ["Retirer aussitôt", "Ne jamais desserrer sans avis médical", "Le desserrer chaque 10 min", "Le mouiller"], 1],
        ["14", "Position d'un blessé hémorragique majeur :", ["Debout", "Allongée, jambes surélevées si possible, oxygénothérapie", "Assise", "Ventrale"], 1],
        ["15", "Un patient hémorragique doit être :", ["Refroidi", "Réchauffé (prévention hypothermie / triade létale)", "Aspergé", "Immergé"], 1],
      ]),
    },
  ],
};

// ============================================================
// UNITÉ 6 — ANATOMIE APPLIQUÉE
// ============================================================
const ANAT: Unit = {
  id: "dea-anat",
  title: "Anatomie appliquée",
  subtitle: "Repères utiles en pré-hospitalier",
  color: "primary",
  icon: "🫀",
  lessons: [
    {
      id: "dea-ana-1",
      title: "Cardio-vasculaire & respiratoire",
      emoji: "❤️",
      questions: mk("dea-anat", "dea-ana-1", [
        ["1", "Le cœur possède :", ["2 cavités", "3 cavités", "4 cavités", "5 cavités"], 2],
        ["2", "Le sang oxygéné revient au cœur par :", ["Veines caves", "Veines pulmonaires", "Artères pulmonaires", "Aorte"], 1],
        ["3", "La plus grosse artère du corps :", ["Fémorale", "Aorte", "Carotide", "Sous-clavière"], 1],
        ["4", "Le pouls carotidien se prend :", ["Au poignet", "Sur le cou, à côté de la trachée", "Sur l'aine", "Sur la cheville"], 1],
        ["5", "Le pouls radial est au :", ["Cou", "Poignet, côté pouce", "Aine", "Genou"], 1],
        ["6", "Le pouls fémoral se prend :", ["Au cou", "Au pli inguinal", "Au coude", "Au front"], 1],
        ["7", "La trachée se divise en :", ["Alvéoles", "2 bronches souches", "Œsophage", "Larynx"], 1],
        ["8", "Le poumon droit compte :", ["1 lobe", "2 lobes", "3 lobes", "4 lobes"], 2],
        ["9", "Les échanges gazeux se font au niveau des :", ["Bronches", "Alvéoles", "Trachée", "Larynx"], 1],
        ["10", "Le diaphragme est :", ["Un os", "Le muscle principal de la respiration", "Une valve", "Une artère"], 1],
      ]),
    },
    {
      id: "dea-ana-2",
      title: "Neurologie & rachis",
      emoji: "🧠",
      questions: mk("dea-anat", "dea-ana-2", [
        ["1", "Le SNC comprend :", ["Cerveau + moelle épinière", "Cœur + poumons", "Foie + rate", "Rein + surrénales"], 0],
        ["2", "La colonne vertébrale contient :", ["Le cœur", "La moelle épinière", "Le foie", "L'estomac"], 1],
        ["3", "Combien de vertèbres cervicales ?", ["5", "7", "12", "24"], 1],
        ["4", "Combien de vertèbres thoraciques (dorsales) ?", ["7", "10", "12", "15"], 2],
        ["5", "Combien de vertèbres lombaires ?", ["3", "5", "7", "12"], 1],
        ["6", "Le sacrum est composé de :", ["Vertèbres mobiles", "Vertèbres soudées", "Cartilage seul", "Rien"], 1],
        ["7", "Une atteinte médullaire haute (cervicale) peut donner :", ["Tétraplégie et détresse respiratoire", "Rhume", "Fièvre isolée", "Douleur genou"], 0],
        ["8", "Le cervelet contrôle :", ["Digestion", "Équilibre et coordination", "Vision", "Audition"], 1],
        ["9", "Le tronc cérébral contrôle :", ["Fonctions vitales (respi, cœur)", "L'humeur uniquement", "La marche", "La glycémie"], 0],
        ["10", "Une suspicion de traumatisme rachidien impose :", ["Marche", "Immobilisation en axe et mobilisation prudente", "Rotation forcée", "Position assise"], 1],
      ]),
    },
    {
      id: "dea-ana-3",
      title: "Squelette & articulations",
      emoji: "🦴",
      questions: mk("dea-anat", "dea-ana-3", [
        ["1", "Os le plus long du corps :", ["Tibia", "Fémur", "Humérus", "Fibula"], 1],
        ["2", "Os du bras :", ["Fémur", "Humérus", "Radius", "Cubitus"], 1],
        ["3", "L'avant-bras contient :", ["Fémur et tibia", "Radius et ulna", "Humérus et clavicule", "Rotule et péroné"], 1],
        ["4", "La rotule protège :", ["La hanche", "Le genou", "Le coude", "L'épaule"], 1],
        ["5", "Le calcanéus est :", ["L'os du talon", "Un os du poignet", "Un os du crâne", "Un os de la main"], 0],
        ["6", "Une fracture ouverte se caractérise par :", ["Aucune plaie", "Une plaie en regard du foyer", "Une simple ecchymose", "Rougeur isolée"], 1],
        ["7", "Une luxation est :", ["Une entorse", "Un déplacement anormal et permanent des surfaces articulaires", "Une fracture", "Une contusion"], 1],
        ["8", "Une entorse est :", ["Étirement/déchirure ligamentaire", "Fracture osseuse", "Luxation", "Section musculaire"], 0],
        ["9", "Le bassin contient notamment :", ["Vessie, rectum, utérus (si femme)", "Cœur et poumons", "Cerveau", "Foie et rate"], 0],
        ["10", "Une fracture du bassin peut :", ["Être bénigne toujours", "Provoquer une hémorragie majeure", "N'a aucun risque", "Ne pas exister"], 1],
      ]),
    },
    {
      id: "dea-ana-4",
      title: "Abdomen & bassin",
      emoji: "🫄",
      questions: mk("dea-anat", "dea-ana-4", [
        ["1", "Le foie se trouve :", ["Hypocondre gauche", "Hypocondre droit", "Fosse iliaque gauche", "Rétro-sternal"], 1],
        ["2", "L'appendice est classiquement :", ["Fosse iliaque droite", "Hypocondre gauche", "Épigastre", "Flanc gauche"], 0],
        ["3", "Une douleur épigastrique peut évoquer :", ["Angine de poitrine, ulcère, pancréatite", "Uniquement une carie", "Uniquement une entorse", "Otite"], 0],
        ["4", "Les reins sont situés :", ["Dans le thorax", "Dans la région lombaire (rétropéritonéaux)", "Dans le pelvis strictement", "Dans le crâne"], 1],
        ["5", "L'estomac se trouve :", ["Fosse iliaque droite", "Épigastre - hypocondre gauche", "Hypocondre droit", "Cou"], 1],
        ["6", "Une douleur en fosse iliaque droite avec fièvre évoque :", ["Appendicite", "Rhume", "Otite", "Sinusite"], 0],
        ["7", "Une douleur lombaire irradiant vers organes génitaux :", ["Colique néphrétique probable", "Crise d'asthme", "Angine", "AVC"], 0],
        ["8", "Une défense abdominale généralisée évoque :", ["Un péritonite / urgence chirurgicale", "Un rhume", "Une constipation banale", "Une carie"], 0],
        ["9", "La grossesse extra-utérine est une urgence :", ["Digestive", "Gynécologique et vitale", "Neurologique", "Cutanée"], 1],
        ["10", "Le péritoine est :", ["Un muscle", "La membrane qui enveloppe les organes abdominaux", "Un os", "Une valve"], 1],
      ]),
    },
  ],
};

// ============================================================
// UNITÉ 7 — PATHOLOGIES
// ============================================================
const PATHO: Unit = {
  id: "dea-patho",
  title: "Pathologies pré-hospitalières",
  subtitle: "Ce que tu rencontreras",
  color: "destructive",
  icon: "⚕️",
  lessons: [
    {
      id: "dea-pat-1",
      title: "Cardiologie",
      emoji: "❤️‍🩹",
      questions: mk("dea-patho", "dea-pat-1", [
        ["1", "L'infarctus du myocarde est :", ["Nécrose du muscle cardiaque par obstruction coronaire", "Une inflammation du foie", "Un problème digestif", "Une allergie"], 0],
        ["2", "La douleur typique de l'IDM :", ["Piqûre passagère", "Douleur rétrosternale constrictive, irradiant bras/mâchoire, > 20 min", "Douleur au genou", "Céphalée frontale"], 1],
        ["3", "Face à un IDM suspecté :", ["Faire marcher", "Repos strict, alerte 15, O₂ si SpO₂<94 %", "Faire vomir", "Rentrer à pied"], 1],
        ["4", "L'angor stable :", ["Douleur à l'effort, cède au repos", "Douleur permanente 24h/24", "Aucune douleur", "Douleur uniquement nocturne"], 0],
        ["5", "Une tachycardie est :", ["FC < 60 bpm", "FC > 100 bpm adulte au repos", "Absence de pouls", "FC normale"], 1],
        ["6", "Une bradycardie est :", ["FC > 100 bpm", "FC < 60 bpm adulte au repos", "FC normale", "Absence de pouls"], 1],
        ["7", "Un OAP est :", ["Une déshydratation", "Un œdème aigu du poumon par insuffisance cardiaque gauche", "Une allergie", "Une infection"], 1],
        ["8", "Signes d'OAP :", ["Fièvre isolée", "Dyspnée, orthopnée, crépitants, expectorations mousseuses", "Diarrhée", "Céphalée"], 1],
        ["9", "L'HTA maligne se définit par :", ["TA normale", "TA très élevée + retentissement (encéphalopathie, OAP…)", "Fièvre", "Hypoglycémie"], 1],
        ["10", "Un patient sous anticoagulants qui saigne :", ["Rien de spécial", "Doit être transporté rapidement, tracer le traitement", "Doit courir", "Doit boire alcool"], 1],
      ]),
    },
    {
      id: "dea-pat-2",
      title: "Neurologie",
      emoji: "🧠",
      questions: mk("dea-patho", "dea-pat-2", [
        ["1", "L'AVC ischémique représente :", ["10 % des AVC", "≈ 80 % des AVC", "50 %", "100 %"], 1],
        ["2", "L'AIT est :", ["Un AVC permanent", "Un déficit transitoire, régressif < 24 h, sentinelle d'AVC", "Une méningite", "Un traumatisme"], 1],
        ["3", "La crise d'épilepsie généralisée :", ["Perte de conscience + convulsions", "Douleur thoracique", "Aphasie isolée", "Fièvre isolée"], 0],
        ["4", "Un état de mal épileptique :", ["Crise < 30 s", "Crise > 5 min ou crises rapprochées sans reprise de conscience", "Une simple absence", "Rien de grave"], 1],
        ["5", "Une méningite peut associer :", ["Céphalée, fièvre, raideur de nuque, photophobie", "Rhume banal", "Otite isolée", "Rien"], 0],
        ["6", "Le purpura fulminans est :", ["Éruption bénigne", "Purpura extensif nécrotique + fièvre → urgence vitale", "Allergie légère", "Sudation"], 1],
        ["7", "Une confusion aiguë chez la personne âgée peut évoquer :", ["Une infection, une hypoglycémie, un AVC, une déshydratation…", "Rien à explorer", "De la simulation", "Rien"], 0],
        ["8", "Une paralysie faciale asymétrique brutale :", ["Doit faire évoquer un AVC", "Est toujours bénigne", "Est un stress", "Ne se voit pas"], 0],
        ["9", "Un syndrome méningé + fièvre chez l'enfant :", ["Attendre 24 h", "Urgence, appel 15", "Donner du chocolat", "Faire un bain froid"], 1],
        ["10", "Un traumatisme crânien sévère avec perte de conscience :", ["Repos maison", "Transport rapide vers structure adaptée", "Course à pied", "Ignorer"], 1],
      ]),
    },
    {
      id: "dea-pat-3",
      title: "Endocrino & métabolisme",
      emoji: "🧪",
      questions: mk("dea-patho", "dea-pat-3", [
        ["1", "L'hypoglycémie est définie par :", ["Glycémie < 0,6 g/L avec signes", "Glycémie > 2 g/L", "Glycémie normale", "Rien"], 0],
        ["2", "Signes d'hypoglycémie :", ["Sueurs, tremblements, faim, confusion, coma", "Fièvre isolée", "Ronflement", "Ictère"], 0],
        ["3", "Un patient conscient hypoglycémique reçoit :", ["Rien", "Sucres rapides per os (15 g) puis lents", "IV directement", "Adrénaline"], 1],
        ["4", "Un patient inconscient hypoglycémique :", ["Peut boire du jus", "Ne doit rien recevoir per os, alerte 15, PLS, O₂ si besoin", "Doit être giflé", "Se relève seul"], 1],
        ["5", "L'acido-cétose diabétique est :", ["Une hypoglycémie", "Complication d'hyperglycémie majeure (souvent DT1)", "Bénigne", "Un rhume"], 1],
        ["6", "Signes d'acido-cétose :", ["Polyurie, polydipsie, dyspnée de Kussmaul, haleine acétonique", "Constipation isolée", "Otite", "Rien"], 0],
        ["7", "Une hyperthermie majeure (>40°C) :", ["Est banale", "Est une urgence, hydratation + refroidissement + appel 15", "Se traite avec un pull", "N'existe pas"], 1],
        ["8", "L'hypothermie sévère :", ["> 35 °C", "< 28 °C, risque d'arrêt cardiaque, réchauffement prudent", "= 36,5 °C", "N'existe pas"], 1],
        ["9", "Une crise d'insuffisance surrénalienne aiguë :", ["Est banale", "Est une urgence (asthénie, hypoTA, hyponatrémie…)", "Se soigne au thé", "N'existe pas"], 1],
        ["10", "Une déshydratation sévère se traduit par :", ["Yeux creux, pli cutané, oligurie, tachycardie", "Fièvre isolée", "Céphalée seule", "Rien"], 0],
      ]),
    },
    {
      id: "dea-pat-4",
      title: "Respiratoire",
      emoji: "🫁",
      questions: mk("dea-patho", "dea-pat-4", [
        ["1", "L'asthme est une pathologie :", ["Cardiaque", "Bronchique inflammatoire réversible", "Digestive", "Osseuse"], 1],
        ["2", "Une crise d'asthme grave nécessite :", ["Position assise, O₂, bronchodilatateur, alerte 15", "Marcher", "Boire du vin", "Rien"], 0],
        ["3", "La BPCO est :", ["Aiguë et réversible", "Chronique obstructive irréversible", "Digestive", "Neurologique"], 1],
        ["4", "Chez un BPCO en détresse, l'O₂ se titre :", ["À 15 L/min systématiquement", "Progressivement pour cible SpO₂ 88-92 %", "Aucun O₂", "5 min max"], 1, "Objectif de saturation plus bas pour éviter l'hypercapnie."],
        ["5", "L'embolie pulmonaire se manifeste par :", ["Dyspnée brutale, douleur thoracique, tachycardie, désaturation", "Fièvre isolée", "Céphalée seule", "Constipation"], 0],
        ["6", "Un pneumothorax spontané peut donner :", ["Douleur thoracique + dyspnée soudaine", "Rien", "Fièvre isolée", "Constipation"], 0],
        ["7", "Un pneumothorax compressif :", ["Est bénin", "Est une urgence vitale (choc, déviation trachée)", "Ne se voit pas", "Se traite au chaud"], 1],
        ["8", "Une pneumonie s'accompagne souvent de :", ["Fièvre, toux, dyspnée, douleur thoracique", "Rien", "Diarrhée isolée", "Constipation"], 0],
        ["9", "Une hyperventilation psychogène :", ["Nécessite un sac plastique", "Se prend en charge par respiration guidée + rassurer", "Se traite à l'oxygène pur", "Est mortelle"], 1],
        ["10", "Un patient sous oxygène doit :", ["Fumer près de la bouteille", "Ne pas fumer, éviter graisses, source d'ignition", "Se lever brutalement", "Boire de l'alcool"], 1],
      ]),
    },
    {
      id: "dea-pat-5",
      title: "Digestif, uro, allergies, intoxications",
      emoji: "🧫",
      questions: mk("dea-patho", "dea-pat-5", [
        ["1", "Une hémorragie digestive haute peut donner :", ["Hématémèse, méléna", "Constipation isolée", "Céphalée seule", "Rien"], 0],
        ["2", "Un abdomen chirurgical se caractérise par :", ["Douleur diffuse, défense, contracture", "Rien", "Rougeur cutanée seule", "Toux"], 0],
        ["3", "Une colique néphrétique typique :", ["Douleur lombaire brutale irradiant génitaux", "Céphalée frontale", "Douleur épaule", "Toux"], 0],
        ["4", "Une réaction anaphylactique se traduit par :", ["Éruption + œdème + hypoTA + bronchospasme + tachycardie", "Rhume", "Constipation", "Rien"], 0],
        ["5", "Face à un choc anaphylactique :", ["Rien", "Position, O₂, alerte 15, éviction allergène, adrénaline (si prescrite)", "Bain chaud", "Boire du lait"], 1],
        ["6", "Le CO (monoxyde de carbone) est :", ["Un gaz odorant", "Un gaz inodore, incolore, toxique", "Un solide", "Un liquide"], 1],
        ["7", "Face à une intoxication au CO :", ["Rester dans le local", "Extraire à l'air libre, O₂ à haut débit, alerte 15/18", "Fumer", "Faire du sport"], 1],
        ["8", "Une intoxication médicamenteuse :", ["Est bénigne", "Doit être signalée, garder emballages, transport pour évaluation", "S'ignore", "N'a pas d'importance"], 1],
        ["9", "Une overdose opioïdes se manifeste par :", ["Myosis, bradypnée, coma", "Mydriase, tachypnée, agitation isolée", "Fièvre isolée", "Rien"], 0],
        ["10", "En cas d'intoxication éthylique aiguë :", ["Faire boire du café", "Surveillance, PLS si troubles de conscience, protection", "Faire vomir systématiquement", "Ignorer"], 1],
      ]),
    },
  ],
};

// ============================================================
// UNITÉ 8 — TRAUMATOLOGIE
// ============================================================
const TRAUMA: Unit = {
  id: "dea-trauma",
  title: "Traumatologie",
  subtitle: "Fractures, plaies, brûlures",
  color: "warning",
  icon: "🩹",
  lessons: [
    {
      id: "dea-tra-1",
      title: "Traumatismes des membres",
      emoji: "🦵",
      questions: mk("dea-trauma", "dea-tra-1", [
        ["1", "Une fracture ouverte associe :", ["Une plaie en regard du foyer + risque infectieux", "Aucune plaie", "Une simple rougeur", "Rien"], 0],
        ["2", "L'immobilisation d'une fracture doit :", ["Croiser une articulation", "Immobiliser l'articulation sus et sous-jacente", "Serrer très fort", "Laisser bouger"], 1],
        ["3", "Face à une déformation évidente :", ["Réduire soi-même", "Immobiliser dans la position trouvée sauf compromis vasculo-nerveux", "Étirer", "Ignorer"], 1],
        ["4", "Avant/après immobilisation, on vérifie :", ["Rien", "Sensibilité, motricité, coloration, pouls distal", "Uniquement la couleur", "La glycémie"], 1],
        ["5", "Une entorse grave (ligamentaire) impose :", ["Marche forcée", "Immobilisation, glace, élévation, avis médical", "Massage puissant", "Rien"], 1],
        ["6", "Une luxation :", ["Se réduit sur place", "Se laisse en place, immobilisation, transport", "S'étire", "S'écrase"], 1],
        ["7", "Face à une amputation :", ["Segment jeté", "Segment enveloppé propre, conservé au frais sans contact glace direct", "Segment recousu sur place", "Segment lavé au savon"], 1],
        ["8", "La règle « PEC (Protection-Repos-Immobilisation-Compression-Élévation) » :", ["Ne s'applique pas", "Peut guider une entorse simple", "S'applique à un ACR", "S'applique à un IDM"], 1],
        ["9", "Une fracture fermée peut se compliquer de :", ["Rien", "Ischémie distale, syndrome des loges, embolie graisseuse", "Digestion", "Rhume"], 1],
        ["10", "Un traumatisme du bassin peut :", ["Être bénin systématiquement", "Entraîner une hémorragie interne majeure", "N'avoir aucune conséquence", "Se traiter au chaud"], 1],
      ]),
    },
    {
      id: "dea-tra-2",
      title: "Traumatismes rachis & crâne",
      emoji: "🧠",
      questions: mk("dea-trauma", "dea-tra-2", [
        ["1", "Face à un traumatisme crânien avec PC :", ["Repos maison", "Bilan neurologique, surveillance, transport pour évaluation", "Faire du sport", "Boire de l'alcool"], 1],
        ["2", "Signes de gravité d'un TC :", ["Vomissements répétés, céphalée intense, troubles conscience, convulsions", "Simple bosse indolore", "Rougeur cutanée seule", "Rien"], 0],
        ["3", "Un patient inconscient traumatique :", ["Marche debout", "Doit être immobilisé en axe et transporté rapidement", "Doit boire", "Doit rentrer chez lui"], 1],
        ["4", "L'immobilisation du rachis cervical se fait avec :", ["Un simple oreiller", "Un collier cervical adapté + immobilisation en axe", "Une écharpe", "Rien"], 1],
        ["5", "Le retournement d'un traumatisé se fait :", ["Seul, rapidement", "À plusieurs, en axe (log-roll), maintien tête", "Sans précaution", "En roulant fortement"], 1],
        ["6", "Un « lésion complète » de moelle cervicale peut donner :", ["Tétraplégie + détresse ventilatoire", "Rhume", "Céphalée seule", "Rien"], 0],
        ["7", "Sur un blessé grave, retirer un casque intégral se fait :", ["Seul en tirant fort", "À 2 sauveteurs, maintien du rachis en axe", "Pas nécessaire", "En le sciant sans précaution"], 1],
        ["8", "L'échelle de Glasgow après TC guide :", ["La gravité et la conduite", "La couleur de la peau", "La faim", "Le sommeil"], 0],
        ["9", "Face à une otorragie ou rhinorrhée claire après TC :", ["Bénigne", "Peut évoquer une fracture de la base du crâne", "Rien", "À boire"], 1],
        ["10", "L'immobilisation en axe s'arrête :", ["Dès l'arrivée sur place", "Sur décision médicale après évaluation radiologique", "Après 5 min", "Jamais"], 1],
      ]),
    },
    {
      id: "dea-tra-3",
      title: "Brûlures, plaies, environnement",
      emoji: "🔥",
      questions: mk("dea-trauma", "dea-tra-3", [
        ["1", "Une brûlure du 1er degré atteint :", ["L'épiderme (rougeur simple)", "Le muscle", "L'os", "Le cœur"], 0],
        ["2", "Le 2e degré superficiel se caractérise par :", ["Phlyctènes + douleur intense", "Absence de douleur", "Fracture", "Rougeur seule"], 0],
        ["3", "Le 3e degré :", ["Douloureux uniquement", "Indolore, aspect cartonné, brun/noir", "Rouge simple", "Bénin"], 1],
        ["4", "La règle des 9 (Wallace) évalue :", ["La surface brûlée en % de surface corporelle", "La profondeur uniquement", "Le poids", "L'âge"], 0],
        ["5", "Face à une brûlure thermique récente :", ["Beurre", "Refroidissement à l'eau tempérée (~15-25 °C) 10-20 min", "Glace en contact direct", "Alcool"], 1],
        ["6", "Une brûlure chimique :", ["Se laisse", "Rinçage abondant à l'eau, retrait vêtements imbibés (EPI)", "Se sèche", "Se traite au beurre"], 1],
        ["7", "Une brûlure électrique :", ["Peut avoir un point d'entrée/sortie et lésions internes graves", "Est toujours bénigne", "Ne concerne que la peau", "Ne se voit pas"], 0],
        ["8", "Face à une hypothermie :", ["Réchauffement brutal", "Réchauffement progressif, manipulation prudente", "Bain froid", "Rien"], 1],
        ["9", "Face à un coup de chaleur :", ["Attendre", "Éviction chaleur, dévêtir, refroidissement, hydratation prudente", "Bain chaud", "Rester au soleil"], 1],
        ["10", "Face à une plaie franche non hémorragique :", ["Nettoyage à l'eau/sérum + pansement propre + bilan tétanos", "Coudre soi-même", "Rincer au vin", "Rien"], 0],
      ]),
    },
  ],
};

// ============================================================
// UNITÉ 9 — SITUATIONS SPÉCIALES
// ============================================================
const SPE: Unit = {
  id: "dea-spe",
  title: "Situations spéciales",
  subtitle: "Obstétrique, pédiatrie, gériatrie, psy",
  color: "accent",
  icon: "👶",
  lessons: [
    {
      id: "dea-spe-1",
      title: "Obstétrique d'urgence",
      emoji: "🤰",
      questions: mk("dea-spe", "dea-spe-1", [
        ["1", "Chez la femme enceinte > 6 mois inconsciente qui respire :", ["PLS gauche", "Décubitus dorsal", "PLS droite", "Debout"], 0],
        ["2", "Une contraction de plus en plus rapprochée + envie de pousser :", ["Attendre le lendemain", "Accouchement imminent → alerte 15, préparer", "Faire marcher", "Ignorer"], 1],
        ["3", "L'expulsion de la tête se fait :", ["Sans soutien", "En soutenant la tête sans tirer, contrôlant le dégagement", "En tirant fort", "En pressant l'abdomen"], 1],
        ["4", "Après la naissance, le cordon :", ["Se coupe immédiatement à main nue", "Se clampe stérilement à distance puis se coupe si consigne", "Se noue", "Se tire"], 1],
        ["5", "Un nouveau-né qui ne crie pas :", ["Attendre 5 min", "Séchage, stimulation, ventilation si besoin", "Bain froid", "Ignorer"], 1],
        ["6", "L'hémorragie du post-partum :", ["Est bénigne", "Est une urgence vitale, appel 15, massage utérin externe possible", "Se soigne au thé", "S'ignore"], 1],
        ["7", "Une éclampsie associe :", ["Céphalée + HTA + convulsions chez une femme enceinte", "Une simple nausée", "Un rhume", "Une constipation"], 0],
        ["8", "Une menace d'accouchement prématuré :", ["Alerte 15, transport doux, décubitus latéral gauche", "Marche rapide", "Sport", "Se coucher au sol"], 0],
        ["9", "Une grossesse extra-utérine rompue :", ["Douleur pelvienne + choc → urgence vitale", "Bénigne", "Rien", "Céphalée isolée"], 0],
        ["10", "Face à une procidence du cordon :", ["Ignorer", "Position genu-pectorale, refoulement de la présentation, alerte 15", "Marche", "Pousser"], 1],
      ]),
    },
    {
      id: "dea-spe-2",
      title: "Pédiatrie & nourrisson",
      emoji: "👶",
      questions: mk("dea-spe", "dea-spe-2", [
        ["1", "La FR normale d'un nourrisson :", ["12/min", "30-50/min", "8/min", "80/min"], 1],
        ["2", "La FC normale d'un nourrisson au repos :", ["60 bpm", "100-160 bpm", "40 bpm", "200 bpm"], 1],
        ["3", "Le triangle d'évaluation pédiatrique évalue :", ["Aspect, respiration, circulation cutanée", "TA seule", "Fièvre seule", "SpO₂ seule"], 0],
        ["4", "Chez le nourrisson qui s'étouffe (obstruction totale, conscient) :", ["Heimlich abdominal", "5 tapes dorsales + 5 compressions thoraciques", "Boire", "Rien"], 1],
        ["5", "Une convulsion fébrile simple :", ["Se traite en calmant la fièvre + surveillance", "Nécessite gifle", "Nécessite bain glacé", "Est mortelle"], 0],
        ["6", "Un enfant hyperthermique :", ["Doit être couvert d'un plaid épais", "Doit être dévêtu, hydraté, refroidi doucement", "Doit boire de l'alcool", "Doit rester couché lourdement"], 1],
        ["7", "Signes de déshydratation grave chez le nourrisson :", ["Yeux creux, pli cutané, fontanelle déprimée, oligurie", "Cheveux gras", "Rien", "Bruits digestifs"], 0],
        ["8", "Le RCP nourrisson : ratio à 2 sauveteurs pro :", ["30/2", "15/2", "5/1", "50/1"], 1],
        ["9", "Emplacement compressions nourrisson :", ["Milieu du sternum, juste sous ligne intermammaire", "Sur l'abdomen", "Sur le cou", "Sur la clavicule"], 0],
        ["10", "Face à un bébé secoué suspecté :", ["Ignorer", "Alerte 15, protection enfant, tracer, signaler", "Gronder les parents", "Rentrer"], 1],
      ]),
    },
    {
      id: "dea-spe-3",
      title: "Gériatrie, psychiatrie, social",
      emoji: "👵",
      questions: mk("dea-spe", "dea-spe-3", [
        ["1", "Chez la personne âgée, une confusion brutale évoque :", ["Un événement aigu (infection, AVC, iatrogénie…)", "De la simulation", "Un caprice", "Rien"], 0],
        ["2", "La chute d'une personne âgée :", ["N'a pas d'importance", "Peut révéler une pathologie aiguë sous-jacente", "Est toujours bénigne", "S'ignore"], 1],
        ["3", "L'ostéoporose favorise :", ["Fracture spontanée", "Croissance", "Contraction musculaire", "Digestion"], 0],
        ["4", "La maltraitance chez la personne âgée :", ["Se signale via voies dédiées", "S'ignore", "Se cache", "Est banale"], 0],
        ["5", "Face à un patient délirant/agressif :", ["Le contenir seul par la force", "Sécuriser, dialogue, appel forces de l'ordre + régulation si besoin", "Provoquer", "Fuir en abandonnant"], 1],
        ["6", "Une crise suicidaire :", ["Se minimise", "S'écoute, se transmet, oriente vers évaluation psychiatrique", "S'ignore", "Se moque"], 1],
        ["7", "Une SDF prise en charge :", ["A moins de droits", "A les mêmes droits, même prise en charge", "Se refuse", "Se laisse dehors"], 1],
        ["8", "Un patient sous curatelle/tutelle :", ["Ne consent pas", "Est informé et son représentant est associé selon la loi", "Est ignoré", "Décide seul de tout"], 1],
        ["9", "Une chute avec impossibilité de se relever évoque :", ["Fracture de hanche notamment (col du fémur)", "Rien", "Un rhume", "Une carie"], 0],
        ["10", "Une désorientation temporo-spatiale isolée nouvelle :", ["N'est jamais grave", "Doit être explorée (AVC, infection, métabolique…)", "Se traite chez soi", "Est un caprice"], 1],
      ]),
    },
  ],
};

// ============================================================
// UNITÉ 10 — RÉGLEMENTATION & TRANSPORT
// ============================================================
const REGL: Unit = {
  id: "dea-regl",
  title: "Réglementation & transport",
  subtitle: "Cadre légal, éthique, RGPD",
  color: "primary",
  icon: "📜",
  lessons: [
    {
      id: "dea-reg-1",
      title: "Cadre légal & profession",
      emoji: "⚖️",
      questions: mk("dea-regl", "dea-reg-1", [
        ["1", "L'ambulancier DEA est :", ["Un professionnel de santé (Code Santé Publique)", "Un simple chauffeur", "Un médecin", "Un pompier"], 0],
        ["2", "Le secret professionnel s'applique :", ["Uniquement au médecin", "À toute personne intervenant dans le système de santé", "Uniquement en public", "Uniquement à l'hôpital"], 1],
        ["3", "Le transport sanitaire est régi par :", ["Le Code de la route uniquement", "Le Code de la Santé Publique", "Le Code civil uniquement", "Aucun texte"], 1],
        ["4", "L'ATSU est :", ["Association de Transports Sanitaires d'Urgence", "Assistance Technique Sécurité Urbaine", "Assurance", "Un examen"], 0],
        ["5", "La garde départementale ambulancière :", ["Est une obligation par département", "N'existe pas", "Est facultative", "Est privée uniquement"], 0],
        ["6", "L'usage de l'avertisseur sonore et lumineux :", ["Est libre", "Est réservé aux situations d'urgence justifiées", "Est esthétique", "Est interdit"], 1],
        ["7", "En intervention prioritaire :", ["On grille tous les feux à toute vitesse", "On dispose de dérogations sous conditions et prudence maximale", "On ignore le code", "On roule à contresens sans restriction"], 1],
        ["8", "L'obligation d'assistance à personne en péril :", ["N'existe pas", "Est légale (art. 223-6 Code pénal)", "Est facultative", "Est réservée aux médecins"], 1],
        ["9", "Face à un refus de soins d'un patient lucide :", ["Forcer", "Respecter, informer, tracer, prévenir la régulation", "Ignorer", "Menacer"], 1],
        ["10", "Le DEA a le devoir de :", ["Diagnostiquer", "Réaliser bilans, gestes d'urgence, transports adaptés dans son champ", "Prescrire", "Opérer"], 1],
      ]),
    },
    {
      id: "dea-reg-2",
      title: "Transport, matériel, RGPD",
      emoji: "🚨",
      questions: mk("dea-regl", "dea-reg-2", [
        ["1", "Un ASSU (ambulance) doit disposer notamment :", ["D'un simple brancard", "Brancard, chaise, aspiration, O₂, DAE, matériel bilan…", "Rien", "D'un vélo"], 1],
        ["2", "La bouteille d'oxygène en cabine :", ["Se fixe fermement", "Se laisse rouler", "Se met à l'envers", "Se pose sur le patient"], 0],
        ["3", "Une bouteille d'O₂ doit être :", ["Manipulée sans précaution", "Éloignée graisses, chocs, sources d'ignition", "Stockée au feu", "Peinte à l'huile"], 1],
        ["4", "Le manomètre indique :", ["La pression restante dans la bouteille", "La température du patient", "La glycémie", "La TA"], 0],
        ["5", "Une bouteille pleine standard indique environ :", ["10 bars", "200 bars", "500 bars", "1 bar"], 1],
        ["6", "L'entretien du VSL/ASSU :", ["Est du ressort exclusif du garage", "Implique vérifications quotidiennes par l'équipage", "Est facultatif", "Se fait 1x/an"], 1],
        ["7", "Le RGPD impose :", ["De publier les données patient", "De protéger les données personnelles / accès limité au besoin", "De vendre les données", "Rien"], 1],
        ["8", "Un dossier patient sur tablette :", ["Peut circuler sans code", "Doit être protégé par authentification et chiffrement", "Est stocké sur clé USB perso", "Se publie sur réseau social"], 1],
        ["9", "Une photo d'un patient sans consentement :", ["Est autorisée", "Est interdite (droit à l'image + secret pro)", "Est obligatoire", "Est publique"], 1],
        ["10", "Une réquisition ne dispense pas :", ["Du secret professionnel dans les limites du strict nécessaire", "De la sécurité", "De la traçabilité", "Toutes les réponses sont vraies"], 3],
      ]),
    },
  ],
};

export const DEA_UNITS: Unit[] = [
  HYGIENE,
  SECU,
  BILANS,
  DETRESSES,
  GESTES,
  ANAT,
  PATHO,
  TRAUMA,
  SPE,
  REGL,
];
