export const ROADMAP_PALETTES = [
  "emerald",
  "cyan",
  "violet",
  "teal",
  "amber",
  "red",
  "fuchsia",
  "orange",
  "pink",
  "blue",
] as const;

export type RoadmapPalette = (typeof ROADMAP_PALETTES)[number];

export const ROADMAP_ICON_NAMES = [
  "activity",
  "ambulance",
  "baby",
  "bandage",
  "bone",
  "book-open",
  "brain",
  "briefcase-medical",
  "car-front",
  "clipboard-list",
  "dna",
  "droplets",
  "eye",
  "flame",
  "flask",
  "hand-heart",
  "hard-hat",
  "heart-handshake",
  "heart-pulse",
  "messages",
  "microscope",
  "navigation",
  "person-standing",
  "phone",
  "scale",
  "shield-alert",
  "shield-check",
  "shield-plus",
  "siren",
  "spray-can",
  "stethoscope",
  "test-tube",
  "trophy",
  "type",
  "users-round",
  "utensils",
  "wind",
  "zap",
] as const;

export type RoadmapIconName = (typeof ROADMAP_ICON_NAMES)[number];

export interface RoadmapBlockVisual {
  icon: RoadmapIconName;
  palette: RoadmapPalette;
}

export const ROADMAP_BLOCK_VISUALS: Record<string, RoadmapBlockVisual> = {
  "bloc-01": { icon: "book-open", palette: "emerald" },
  "bloc-02": { icon: "person-standing", palette: "cyan" },
  "bloc-03": { icon: "messages", palette: "violet" },
  "bloc-04": { icon: "shield-check", palette: "teal" },
  "bloc-05": { icon: "ambulance", palette: "amber" },
  "bloc-06": { icon: "siren", palette: "red" },
  "bloc-07": { icon: "stethoscope", palette: "fuchsia" },
  "bloc-08": { icon: "bandage", palette: "orange" },
  "bloc-09": { icon: "hand-heart", palette: "pink" },
  "bloc-10": { icon: "briefcase-medical", palette: "blue" },
  "bloc-11": { icon: "heart-pulse", palette: "red" },
  "bloc-12": { icon: "wind", palette: "cyan" },
  "bloc-13": { icon: "brain", palette: "violet" },
  "bloc-14": { icon: "test-tube", palette: "pink" },
  "bloc-15": { icon: "microscope", palette: "teal" },
};

export const ROADMAP_PARCOURS_VISUALS: Record<string, RoadmapIconName> = {
  "parcours-01": "person-standing",
  "parcours-02": "type",
  "parcours-03": "dna",
  "parcours-04": "bone",
  "parcours-05": "heart-pulse",
  "parcours-06": "wind",
  "parcours-07": "utensils",
  "parcours-08": "brain",
  "parcours-09": "droplets",
  "parcours-10": "flask",
  "parcours-11": "eye",
  "parcours-12": "messages",
  "parcours-13": "heart-handshake",
  "parcours-14": "spray-can",
  "parcours-15": "shield-plus",
  "parcours-16": "hard-hat",
  "parcours-17": "clipboard-list",
  "parcours-18": "activity",
  "parcours-19": "wind",
  "parcours-20": "heart-pulse",
  "parcours-21": "brain",
  "parcours-22": "zap",
  "parcours-23": "wind",
  "parcours-24": "briefcase-medical",
  "parcours-25": "heart-pulse",
  "parcours-26": "wind",
  "parcours-27": "brain",
  "parcours-28": "utensils",
  "parcours-29": "test-tube",
  "parcours-30": "droplets",
  "parcours-31": "microscope",
  "parcours-32": "flask",
  "parcours-33": "shield-alert",
  "parcours-34": "bone",
  "parcours-35": "brain",
  "parcours-36": "activity",
  "parcours-37": "flame",
  "parcours-38": "bandage",
  "parcours-39": "baby",
  "parcours-40": "baby",
  "parcours-41": "person-standing",
  "parcours-42": "brain",
  "parcours-43": "hand-heart",
  "parcours-44": "scale",
  "parcours-45": "ambulance",
  "parcours-46": "car-front",
  "parcours-47": "phone",
  "parcours-48": "navigation",
  "parcours-49": "users-round",
  "parcours-50": "trophy",
  "parcours-51": "heart-pulse",
  "parcours-52": "activity",
  "parcours-53": "heart-pulse",
  "parcours-54": "shield-alert",
  "parcours-55": "activity",
  "parcours-56": "wind",
  "parcours-57": "wind",
  "parcours-58": "droplets",
  "parcours-59": "wind",
  "parcours-60": "ambulance",
  "parcours-61": "brain",
  "parcours-62": "brain",
  "parcours-63": "zap",
  "parcours-64": "brain",
  "parcours-65": "activity",
  "parcours-66": "test-tube",
  "parcours-67": "droplets",
  "parcours-68": "flask",
  "parcours-69": "droplets",
  "parcours-70": "dna",
  "parcours-71": "microscope",
  "parcours-72": "shield-alert",
  "parcours-73": "wind",
  "parcours-74": "utensils",
  "parcours-75": "shield-check",
};
