export {
  applyAction,
  type ApplyActionClassification,
  type ApplyActionResult,
} from "./apply-action.ts";
export {
  calculateBilanGaps,
  equipmentBlockedFactIds,
  gapFactIdsV3,
  regulatorQuestionsForSession,
  staleFactIds,
  type BilanGap,
  type BilanGapKind,
} from "./v3-gaps.ts";
export {
  advanceV3Phase,
  nextV3Phase,
  phaseAfterAction,
  transitionV3Phase,
  V3_PHASE_SEQUENCE,
  type PhaseTransitionResult,
} from "./v3-phases.ts";
export {
  graveFaultCount,
  isV3Failure,
  livesFromActionLog,
  rewardFromPerformance,
  scoreAxesFromLog,
  scoreFromActionLog,
} from "./v3-scoring.ts";
export {
  allGestureChoices,
  allRefusedGestures,
  deselectGesture,
  gestureRoundOpenedAt,
  gestureRoundTimeLeft,
  isGestureJustified,
  isGestureRoundExpired,
  missingJustifications,
  resolveGestureRound,
  selectGesture,
  GESTURE_NOT_INDICATED_FLAG,
  GESTURE_REFUSAL_KINDS,
  GESTURE_SCORES,
  GESTURE_UNJUSTIFIED_FLAG,
  type GestureRefusalKind,
  type GestureRoundResolution,
  type GestureSelectionResult,
} from "./v3-gestures.ts";
export {
  currentReevaluation,
  missingExpectedFactIds,
  openReevaluation,
  perishableExpectedFactIds,
  reevaluationStatus,
  refreshedSince,
  reinforcementStatus,
  staleExpectedFactIds,
  staleTransportPenalty,
  transportReadiness,
  validateReevaluation,
  REINFORCEMENT_EN_ROUTE_SECONDS,
  REINFORCEMENT_ON_SCENE_SECONDS,
  STALE_TRANSPORT_FLAG,
  STALE_TRANSPORT_PENALTY_CAP,
  STALE_TRANSPORT_PENALTY_PER_FACT,
  type ReevaluationStatus,
  type ReevaluationValidation,
  type TransportReadiness,
} from "./v3-reevaluation.ts";
export {
  answerRegulatorQuestion,
  buildCentre15Transmission,
  handoverCommunicationScore,
  handoverItemStates,
  handoverOffers,
  regulatorQuestionsForTransmission,
  reviewAdditions,
  unansweredQuestions,
  DIAGNOSTIC_FORMULATION_FLAG,
  HANDOVER_SCORES,
  MAX_ADDITION_BONUS,
  REGULATOR_ANSWER_SCORES,
  SILENT_GAP_FLAG,
  type AdditionReview,
  type HandoverFactOffer,
  type HandoverFactStatus,
  type HandoverItemOffer,
  type HandoverSelection,
  type RegulatorAnswerResult,
} from "./v3-transmission.ts";
export { transmitHandover, type TransmissionResult } from "./v3-handover.ts";
export { createDebriefReport } from "./v3-debrief.ts";
