import type {
  DecisionEffect,
  InterventionScenario,
  PatientSnapshot,
  ScenarioChoice,
  ScenarioStep,
} from "@/features/intervention-domain";

const effect = (
  score: number,
  patient: number,
  timeSeconds: number,
  extra: Partial<DecisionEffect> = {},
): DecisionEffect => ({ score, patient, timeSeconds, ...extra });

const choice = (
  id: string,
  label: string,
  detail: string,
  feedback: string,
  recommended: boolean,
  decisionEffect: DecisionEffect,
  nextStepId?: string,
): ScenarioChoice => ({
  id,
  label,
  detail,
  feedback,
  recommended,
  effect: decisionEffect,
  nextStepId,
});

const patient = (
  label: string,
  detail: string,
  tone: PatientSnapshot["tone"],
  vitals: PatientSnapshot["vitals"],
): PatientSnapshot => ({ label, detail, tone, vitals });

const step = (value: ScenarioStep): ScenarioStep => value;

const chestPain: InterventionScenario = {
  id: "thoracic-58",
  specialty: "Urgence cardiologique",
  title: "Douleur thoracique à domicile",
  summary: "Un homme de 58 ans présente une douleur thoracique brutale avec sueurs et nausées.",
  difficulty: "initiation",
  estimatedMinutes: 8,
  baseXp: 120,
  illustration: "cardiac",
  startingPatient: 58,
  alert: {
    patient: "Homme, 58 ans",
    reason: "Douleur thoracique brutale",
    priority: "Urgence absolue",
    distance: "2,4 km",
    location: "Rue Victor-Hugo, appartement 3B",
    time: "07:42",
    dispatchNote: "Patient conscient. Son épouse est présente. Accès par cour intérieure.",
  },
  reward: {
    coins: 90,
    chest: "Coffre Bronze",
    chestMinimumScore: 68,
    badge: "Sang-froid",
    badgeMinimumScore: 88,
  },
  pulseAdvice: [
    "Annonce ton bilan de façon structurée et concise à la régulation médicale.",
    "Devant une douleur thoracique, le facteur temps compte : reste méthodique sans retarder l'alerte.",
    "Réévalue l'état du patient pendant toute la prise en charge et le transport.",
  ],
  steps: [
    step({
      id: "thoracic-arrival",
      phase: "arrival",
      eyebrow: "Sur les lieux",
      title: "Organiser l'arrivée",
      narrative:
        "Le véhicule est stationné à trente mètres de l'entrée. L'épouse du patient vous fait signe depuis le hall.",
      objective: "Préparer l'équipe avant le contact patient.",
      patient: patient("Patient non visible", "Informations limitées à l'appel initial.", "watch", [
        { label: "Conscience", value: "Signalée conservée", tone: "watch" },
        { label: "Accès", value: "Appartement 3B" },
      ]),
      choices: [
        choice(
          "arrival-kit",
          "Prendre le matériel d'urgence",
          "Préparer bilan, DAE et oxygénothérapie selon protocole.",
          "Bonne anticipation : le matériel essentiel accompagne l'équipe dès le premier contact.",
          true,
          effect(8, 2, 35, { xpBonus: 8 }),
        ),
        choice(
          "arrival-light",
          "Monter sans matériel",
          "Revenir au véhicule uniquement si nécessaire.",
          "Cette décision peut faire perdre un temps précieux si l'état se dégrade.",
          false,
          effect(-7, -5, 75, { isError: true }),
        ),
        choice(
          "arrival-call",
          "Rappeler longuement la régulation",
          "Demander un nouveau résumé avant de monter.",
          "Les informations disponibles suffisent pour débuter l'approche ; le bilan terrain guidera la transmission.",
          false,
          effect(-3, -1, 85),
        ),
      ],
    }),
    step({
      id: "thoracic-safety",
      phase: "safety",
      eyebrow: "Entrée dans le logement",
      title: "Sécuriser la scène",
      narrative:
        "Le patient est assis dans le salon. La pièce est étroite, plusieurs proches sont présents.",
      objective: "Créer un espace sûr et préserver l'intimité.",
      patient: patient(
        "Conscient, anxieux",
        "Il serre sa poitrine et parle par phrases courtes.",
        "watch",
        [
          { label: "Position", value: "Assis penché en avant" },
          { label: "Environnement", value: "Encombré", tone: "watch" },
        ],
      ),
      choices: [
        choice(
          "safety-space",
          "Dégager l'espace et se présenter",
          "Limiter les personnes autour du patient et expliquer l'intervention.",
          "L'environnement devient praticable et le patient comprend ce qui va se passer.",
          true,
          effect(8, 4, 35, { xpBonus: 6 }),
        ),
        choice(
          "safety-move",
          "Faire marcher le patient",
          "Le déplacer vers l'entrée pour gagner de la place.",
          "Un effort imposé à un patient douloureux thoracique peut aggraver son état.",
          false,
          effect(-12, -12, 30, { isError: true }),
        ),
        choice(
          "safety-ignore",
          "Commencer sans sécuriser",
          "Réaliser immédiatement les constantes au milieu des proches.",
          "Le manque d'espace gêne le bilan et augmente le stress du patient.",
          false,
          effect(-5, -3, 50),
        ),
      ],
    }),
    step({
      id: "thoracic-primary",
      phase: "primary",
      eyebrow: "Première minute",
      title: "Réaliser le bilan primaire",
      narrative:
        "Le patient répond correctement mais sa respiration est rapide. Sa peau est pâle et moite.",
      objective: "Rechercher immédiatement une détresse vitale avec une approche structurée.",
      patient: patient(
        "État préoccupant",
        "Douleur constrictive depuis vingt minutes.",
        "critical",
        [
          { label: "FR", value: "24/min", tone: "watch" },
          { label: "SpO₂", value: "94 %", tone: "watch" },
          { label: "Pouls", value: "108/min", tone: "critical" },
          { label: "Conscience", value: "Alerte" },
        ],
      ),
      choices: [
        choice(
          "primary-abcde",
          "Suivre l'approche ABCDE",
          "Contrôler successivement voies aériennes, respiration, circulation, neurologie et exposition.",
          "Le bilan structuré identifie rapidement les signes de gravité et prépare une transmission fiable.",
          true,
          effect(12, 7, 70, { xpBonus: 12, flags: ["structured-primary"] }),
          "thoracic-secondary-stable",
        ),
        choice(
          "primary-pain",
          "Questionner uniquement la douleur",
          "Rechercher localisation, irradiation et intensité avant les constantes.",
          "L'interrogatoire est utile, mais il ne remplace pas la recherche initiale de détresse vitale.",
          false,
          effect(-7, -8, 80, { isError: true, flags: ["primary-delay"] }),
          "thoracic-secondary-unstable",
        ),
        choice(
          "primary-wait",
          "Attendre l'équipe médicale",
          "Installer le patient et ne plus le solliciter.",
          "L'absence de bilan retarde la régulation et la détection d'une aggravation.",
          false,
          effect(-14, -15, 110, { isError: true, flags: ["primary-delay"] }),
          "thoracic-secondary-unstable",
        ),
      ],
    }),
    step({
      id: "thoracic-secondary-stable",
      phase: "secondary",
      eyebrow: "Patient surveillé",
      title: "Compléter le bilan",
      narrative:
        "Le patient reste conscient. Le bilan primaire n'a pas retrouvé de détresse immédiatement réversible.",
      objective: "Préciser l'histoire, les antécédents et l'évolution des symptômes.",
      patient: patient("Stable sous surveillance", "La douleur persiste à 7/10.", "watch", [
        { label: "TA", value: "146/88 mmHg" },
        { label: "Douleur", value: "7/10", tone: "critical" },
        { label: "Glycémie", value: "1,18 g/L" },
      ]),
      choices: [
        choice(
          "secondary-sample",
          "Interrogatoire SAMPLE et douleur",
          "Rechercher allergies, traitements, antécédents, dernier repas et circonstances.",
          "Le recueil est complet et directement exploitable par la régulation médicale.",
          true,
          effect(10, 4, 90, { xpBonus: 10 }),
          "thoracic-care",
        ),
        choice(
          "secondary-family",
          "Questionner seulement l'épouse",
          "Éviter de fatiguer le patient.",
          "L'entourage complète le bilan, mais la parole du patient reste prioritaire s'il peut répondre.",
          false,
          effect(-4, -2, 100),
          "thoracic-care",
        ),
        choice(
          "secondary-skip",
          "Passer au transport",
          "Considérer que la douleur suffit à décider.",
          "Les antécédents et traitements sont essentiels à la décision médicale et à la continuité des soins.",
          false,
          effect(-7, -3, 55, { isError: true }),
          "thoracic-care",
        ),
      ],
    }),
    step({
      id: "thoracic-secondary-unstable",
      phase: "secondary",
      eyebrow: "Aggravation",
      title: "Réagir à la dégradation",
      narrative:
        "Le patient devient plus pâle et décrit des vertiges. Son pouls est difficile à percevoir.",
      objective: "Reprendre immédiatement le bilan vital et demander un renfort adapté.",
      patient: patient(
        "Instabilité circulatoire",
        "Le retard du bilan primaire a masqué l'aggravation.",
        "critical",
        [
          { label: "TA", value: "88/56 mmHg", tone: "critical" },
          { label: "Pouls", value: "122/min", tone: "critical" },
          { label: "Conscience", value: "Confus", tone: "critical" },
        ],
      ),
      choices: [
        choice(
          "unstable-reassess",
          "Reprendre ABCDE et alerter",
          "Installer, surveiller et transmettre sans délai l'aggravation.",
          "La reprise structurée du bilan permet de corriger la trajectoire et d'accélérer le renfort médical.",
          true,
          effect(8, 8, 75, { xpBonus: 6, flags: ["recovered"] }),
          "thoracic-care",
        ),
        choice(
          "unstable-questions",
          "Poursuivre l'interrogatoire",
          "Terminer les antécédents avant de rappeler.",
          "La priorité est désormais la détresse vitale, pas l'exhaustivité de l'interrogatoire.",
          false,
          effect(-12, -14, 90, { isError: true }),
          "thoracic-care",
        ),
        choice(
          "unstable-walk",
          "Évacuer debout immédiatement",
          "Soutenir le patient jusqu'au brancard.",
          "Cette mobilisation est dangereuse chez un patient instable.",
          false,
          effect(-15, -18, 45, { isError: true }),
          "thoracic-care",
        ),
      ],
    }),
    step({
      id: "thoracic-care",
      phase: "care",
      eyebrow: "Prise en charge",
      title: "Choisir les gestes adaptés",
      narrative: "Le matériel est prêt. Le patient reste douloureux et anxieux.",
      objective: "Mettre en œuvre les gestes relevant du protocole et des consignes de régulation.",
      patient: patient(
        "Sous surveillance",
        "L'évolution doit être réévaluée régulièrement.",
        "watch",
        [
          { label: "Douleur", value: "7/10", tone: "critical" },
          { label: "SpO₂", value: "94 %", tone: "watch" },
          { label: "Rythme", value: "Tachycarde", tone: "watch" },
        ],
      ),
      choices: [
        choice(
          "care-monitor",
          "Installer, surveiller et préparer le DAE",
          "Limiter les efforts, rassurer et appliquer les consignes reçues.",
          "Les gestes restent proportionnés, sécurisés et coordonnés avec la régulation.",
          true,
          effect(10, 8, 85, { xpBonus: 10, rewardBonus: 10 }),
        ),
        choice(
          "care-medicate",
          "Donner un médicament disponible",
          "Utiliser le traitement d'un proche pour soulager rapidement.",
          "Aucun médicament ne doit être improvisé hors protocole ou prescription de la régulation.",
          false,
          effect(-16, -16, 55, { isError: true }),
        ),
        choice(
          "care-oxygen",
          "Mettre systématiquement un fort débit",
          "Administrer de l'oxygène sans tenir compte du protocole ni de la saturation.",
          "L'oxygénothérapie doit être adaptée à l'évaluation et aux protocoles applicables.",
          false,
          effect(-7, -4, 55, { isError: true }),
        ),
      ],
    }),
    step({
      id: "thoracic-decision",
      phase: "decision",
      eyebrow: "Régulation",
      title: "Transmettre et décider",
      narrative:
        "Tu dois présenter la situation au médecin régulateur pour définir la suite de la prise en charge.",
      objective: "Fournir un bilan court, hiérarchisé et signaler les signes de gravité.",
      patient: patient(
        "En attente d'orientation",
        "L'état reste sensible au facteur temps.",
        "watch",
        [
          { label: "Évolution", value: "Douleur persistante", tone: "watch" },
          { label: "Surveillance", value: "Continue" },
        ],
      ),
      choices: [
        choice(
          "decision-structured",
          "Transmettre un bilan structuré",
          "Identité, motif, ABCDE, constantes, antécédents, évolution et gestes réalisés.",
          "La régulation dispose des informations critiques pour décider de la filière et des renforts.",
          true,
          effect(12, 8, 75, { xpBonus: 12, rewardBonus: 15 }),
        ),
        choice(
          "decision-short",
          "Dire seulement « douleur thoracique »",
          "Demander directement l'hôpital de destination.",
          "Le motif seul ne permet pas une décision médicale sûre.",
          false,
          effect(-10, -8, 60, { isError: true }),
        ),
        choice(
          "decision-self",
          "Choisir soi-même la destination",
          "Partir vers l'établissement le plus proche sans bilan médical.",
          "L'orientation d'une urgence thoracique doit être coordonnée avec la régulation médicale.",
          false,
          effect(-14, -12, 55, { isError: true }),
        ),
      ],
    }),
    step({
      id: "thoracic-transport",
      phase: "transport",
      eyebrow: "Évacuation",
      title: "Organiser le transport",
      narrative:
        "La régulation confirme l'orientation et demande une surveillance rapprochée pendant le trajet.",
      objective: "Évacuer sans effort inutile et anticiper une aggravation.",
      patient: patient(
        "Transport médicalisé coordonné",
        "Le patient est installé et monitoré selon le dispositif disponible.",
        "watch",
        [
          { label: "Position", value: "Adaptée au confort" },
          { label: "Réévaluation", value: "Régulière" },
        ],
      ),
      choices: [
        choice(
          "transport-carry",
          "Utiliser le moyen de portage adapté",
          "Préparer le trajet, sécuriser le patient et poursuivre la surveillance.",
          "L'évacuation limite les efforts et conserve la continuité du bilan.",
          true,
          effect(10, 6, 110, { xpBonus: 8, rewardBonus: 10 }),
        ),
        choice(
          "transport-walk",
          "Faire descendre le patient à pied",
          "Gagner du temps dans l'escalier.",
          "L'effort est inadapté au contexte et peut entraîner une aggravation brutale.",
          false,
          effect(-16, -18, 65, { isError: true }),
        ),
        choice(
          "transport-stop",
          "Interrompre la surveillance",
          "Ranger le matériel pendant le trajet.",
          "Un patient à risque doit être réévalué jusqu'au relais avec l'équipe receveuse.",
          false,
          effect(-11, -10, 80, { isError: true }),
        ),
      ],
    }),
    step({
      id: "thoracic-handover",
      phase: "debrief",
      eyebrow: "Relais hospitalier",
      title: "Conclure la mission",
      narrative:
        "L'équipe receveuse est prête. Il reste à transmettre et tracer la prise en charge.",
      objective: "Assurer une continuité complète et professionnelle.",
      patient: patient(
        "Pris en charge à l'arrivée",
        "Le relais doit reprendre les informations essentielles.",
        "stable",
        [
          { label: "Relais", value: "Disponible" },
          { label: "Traçabilité", value: "À finaliser" },
        ],
      ),
      choices: [
        choice(
          "handover-full",
          "Faire le relais et tracer",
          "Transmettre l'évolution, les constantes, les gestes et les consignes reçues.",
          "Mission terminée avec une continuité des soins claire et traçable.",
          true,
          effect(10, 4, 80, { xpBonus: 10, rewardBonus: 15 }),
        ),
        choice(
          "handover-brief",
          "Laisser uniquement la fiche",
          "Éviter une transmission orale redondante.",
          "La fiche ne remplace pas un relais oral ciblé lorsque la situation est urgente.",
          false,
          effect(-6, -3, 45, { isError: true }),
        ),
      ],
    }),
  ],
};

const hypoglycemia: InterventionScenario = {
  id: "hypoglycemia-72",
  specialty: "Urgence métabolique",
  title: "Malaise chez une patiente diabétique",
  summary: "Une femme de 72 ans est confuse dans une pharmacie, avec sueurs et tremblements.",
  difficulty: "intermediate",
  estimatedMinutes: 10,
  baseXp: 160,
  illustration: "metabolic",
  unlockAfter: "thoracic-58",
  startingPatient: 48,
  alert: {
    patient: "Femme, 72 ans",
    reason: "Malaise avec confusion",
    priority: "Urgence potentielle",
    distance: "4,1 km",
    location: "Pharmacie des Halles",
    time: "14:18",
    dispatchNote: "Patiente diabétique connue. Personnel de pharmacie présent.",
  },
  reward: {
    coins: 130,
    chest: "Coffre Argent",
    chestMinimumScore: 74,
    badge: "Bilan précis",
    badgeMinimumScore: 90,
  },
  pulseAdvice: [
    "Une modification du comportement impose d'abord une recherche structurée de détresse vitale.",
    "Mesure la glycémie précocement lorsque le contexte l'indique, sans négliger les autres causes possibles.",
    "Vérifie la capacité réelle à avaler avant toute administration par voie orale.",
  ],
  steps: [
    step({
      id: "hypo-arrival",
      phase: "arrival",
      eyebrow: "Commerce ouvert",
      title: "Préparer l'approche",
      narrative: "La pharmacie reste ouverte et plusieurs clients observent la scène.",
      objective: "Identifier le patient, le matériel utile et un espace de prise en charge.",
      patient: patient(
        "Patiente visible au fond du magasin",
        "Assise, soutenue par une pharmacienne.",
        "watch",
        [
          { label: "Conscience", value: "Confuse", tone: "critical" },
          { label: "Contexte", value: "Lieu public" },
        ],
      ),
      choices: [
        choice(
          "hypo-arrival-ready",
          "Prendre le matériel de bilan",
          "Prévoir glycémie, DAE, oxygénothérapie et matériel d'urgence.",
          "L'équipe est prête à rechercher rapidement une cause grave.",
          true,
          effect(8, 3, 35, { xpBonus: 6 }),
        ),
        choice(
          "hypo-arrival-question",
          "Interroger longtemps le personnel",
          "Reconstituer les événements avant d'approcher.",
          "Les témoins sont utiles, mais le premier contact patient ne doit pas être retardé.",
          false,
          effect(-5, -5, 90, { isError: true }),
        ),
      ],
    }),
    step({
      id: "hypo-safety",
      phase: "safety",
      eyebrow: "Protection",
      title: "Protéger la patiente",
      narrative:
        "La patiente risque de glisser de sa chaise et la foule réduit l'espace disponible.",
      objective: "Sécuriser la position, l'intimité et l'accès des secours.",
      patient: patient("Confuse et agitée", "Elle cherche à se lever.", "critical", [
        { label: "Chute", value: "Risque élevé", tone: "critical" },
        { label: "Coopération", value: "Limitée", tone: "watch" },
      ]),
      choices: [
        choice(
          "hypo-safety-space",
          "Sécuriser et dégager l'espace",
          "Accompagner la position, éloigner la foule et se présenter calmement.",
          "Le risque de chute diminue et l'équipe peut travailler efficacement.",
          true,
          effect(9, 6, 40, { xpBonus: 7 }),
        ),
        choice(
          "hypo-safety-stand",
          "La faire marcher dehors",
          "Rechercher un endroit plus calme sur le trottoir.",
          "La marche augmente le risque de chute chez cette patiente confuse.",
          false,
          effect(-12, -12, 35, { isError: true }),
        ),
      ],
    }),
    step({
      id: "hypo-primary",
      phase: "primary",
      eyebrow: "Évaluation immédiate",
      title: "Bilan primaire",
      narrative: "La patiente ouvre les yeux à la voix et prononce des mots incohérents.",
      objective: "Évaluer ABCDE et rechercher une cause rapidement réversible.",
      patient: patient("Altération neurologique", "Sueurs profuses et tremblements.", "critical", [
        { label: "FR", value: "20/min" },
        { label: "SpO₂", value: "97 %" },
        { label: "Pouls", value: "104/min", tone: "watch" },
        { label: "Conscience", value: "V", tone: "critical" },
      ]),
      choices: [
        choice(
          "hypo-primary-abcde",
          "Faire ABCDE puis glycémie",
          "Contrôler les fonctions vitales et mesurer la glycémie capillaire.",
          "La glycémie à 0,42 g/L confirme une hypoglycémie sévère dans un bilan vital complet.",
          true,
          effect(13, 9, 75, { xpBonus: 12, flags: ["hypoglycemia-confirmed"] }),
        ),
        choice(
          "hypo-primary-sugar",
          "Donner immédiatement du sucre",
          "Faire boire avant de tester pour gagner du temps.",
          "La capacité à avaler n'est pas vérifiée : le risque de fausse route est majeur.",
          false,
          effect(-15, -18, 35, { isError: true, flags: ["aspiration-risk"] }),
        ),
        choice(
          "hypo-primary-stroke",
          "Conclure à un AVC",
          "Écarter l'hypoglycémie sans mesure.",
          "Une hypoglycémie peut imiter un déficit neurologique et doit être recherchée précocement.",
          false,
          effect(-10, -12, 100, { isError: true }),
        ),
      ],
    }),
    step({
      id: "hypo-secondary",
      phase: "secondary",
      eyebrow: "Contexte thérapeutique",
      title: "Comprendre l'épisode",
      narrative: "La pharmacienne retrouve une ordonnance récente d'insuline.",
      objective: "Recueillir les traitements, le dernier repas et les circonstances.",
      patient: patient("Hypoglycémie confirmée", "La patiente répond difficilement.", "critical", [
        { label: "Glycémie", value: "0,42 g/L", tone: "critical" },
        { label: "Dernier repas", value: "Inconnu", tone: "watch" },
      ]),
      choices: [
        choice(
          "hypo-secondary-source",
          "Croiser patient, témoin et ordonnance",
          "Rechercher prise d'insuline, repas, allergies et antécédents.",
          "Le bilan retrouve une injection habituelle suivie d'un repas non pris.",
          true,
          effect(10, 4, 90, { xpBonus: 10 }),
        ),
        choice(
          "hypo-secondary-skip",
          "Considérer la cause évidente",
          "Ne pas rechercher d'autre facteur.",
          "Une cause probable ne dispense pas d'un recueil complet et d'une surveillance globale.",
          false,
          effect(-6, -5, 55),
        ),
      ],
    }),
    step({
      id: "hypo-care",
      phase: "care",
      eyebrow: "Geste adapté",
      title: "Corriger sans mettre en danger",
      narrative: "La patiente n'est pas capable d'avaler sur demande.",
      objective: "Appliquer le protocole et obtenir une décision médicale rapide.",
      patient: patient(
        "Trouble de déglutition probable",
        "La protection des voies aériennes est prioritaire.",
        "critical",
        [
          { label: "Déglutition", value: "Non fiable", tone: "critical" },
          { label: "Conscience", value: "Fluctuante", tone: "critical" },
        ],
      ),
      choices: [
        choice(
          "hypo-care-regulation",
          "Protéger et contacter la régulation",
          "Ne rien donner par la bouche, surveiller et appliquer les consignes du protocole.",
          "La conduite évite la fausse route et permet une correction adaptée au niveau de compétence.",
          true,
          effect(13, 12, 70, { xpBonus: 12, rewardBonus: 15 }),
        ),
        choice(
          "hypo-care-drink",
          "Faire boire une boisson sucrée",
          "Maintenir la tête pour aider à avaler.",
          "L'administration orale est dangereuse lorsque la déglutition n'est pas sûre.",
          false,
          effect(-18, -22, 35, { isError: true }),
        ),
      ],
    }),
    step({
      id: "hypo-decision",
      phase: "decision",
      eyebrow: "Bilan au SAMU",
      title: "Présenter la situation",
      narrative: "La régulation attend ton bilan pour confirmer la conduite à tenir.",
      objective: "Transmettre gravité, glycémie, traitements et capacité à avaler.",
      patient: patient("Surveillance rapprochée", "L'état peut évoluer rapidement.", "watch", [
        { label: "Glycémie", value: "0,42 g/L", tone: "critical" },
        { label: "Voie orale", value: "Contre-indiquée", tone: "critical" },
      ]),
      choices: [
        choice(
          "hypo-decision-full",
          "Donner un bilan hiérarchisé",
          "Inclure ABCDE, glycémie, conscience, traitement et dernier repas.",
          "La régulation peut décider rapidement et en sécurité.",
          true,
          effect(12, 8, 70, { xpBonus: 10, rewardBonus: 15 }),
        ),
        choice(
          "hypo-decision-number",
          "Transmettre uniquement la glycémie",
          "Le chiffre suffit à expliquer le malaise.",
          "La valeur doit être interprétée avec l'état clinique et le risque de dégradation.",
          false,
          effect(-9, -8, 55, { isError: true }),
        ),
      ],
    }),
    step({
      id: "hypo-transport",
      phase: "transport",
      eyebrow: "Surveillance",
      title: "Préparer l'évacuation",
      narrative: "La patiente reprend progressivement contact après la conduite prescrite.",
      objective: "Ne pas banaliser l'amélioration et prévenir la récidive.",
      patient: patient(
        "Amélioration partielle",
        "Elle reconnaît la pharmacienne mais reste fatiguée.",
        "watch",
        [
          { label: "Conscience", value: "Alerte" },
          { label: "Glycémie", value: "À recontrôler", tone: "watch" },
        ],
      ),
      choices: [
        choice(
          "hypo-transport-monitor",
          "Transporter avec réévaluations",
          "Recontrôler conscience, glycémie et constantes selon consignes.",
          "L'amélioration est confirmée sans interrompre la surveillance.",
          true,
          effect(10, 7, 105, { xpBonus: 8, rewardBonus: 10 }),
        ),
        choice(
          "hypo-transport-leave",
          "Laisser la patiente sur place",
          "L'amélioration semble suffisante.",
          "La décision de non-transport ne peut pas être improvisée après une altération de conscience.",
          false,
          effect(-16, -20, 40, { isError: true }),
        ),
      ],
    }),
    step({
      id: "hypo-handover",
      phase: "debrief",
      eyebrow: "Relais",
      title: "Transmettre l'évolution",
      narrative: "L'équipe receveuse demande les valeurs successives et la chronologie.",
      objective: "Tracer l'évolution et les actions réalisées.",
      patient: patient(
        "Relais sécurisé",
        "L'évolution complète la compréhension de l'épisode.",
        "stable",
        [
          { label: "Chronologie", value: "Disponible" },
          { label: "Traitement", value: "Identifié" },
        ],
      ),
      choices: [
        choice(
          "hypo-handover-full",
          "Faire un relais chronologique",
          "Présenter état initial, glycémies, actions, réponse et surveillance.",
          "La continuité est complète et utile à la recherche de la cause.",
          true,
          effect(10, 4, 75, { xpBonus: 10, rewardBonus: 15 }),
        ),
        choice(
          "hypo-handover-last",
          "Donner seulement la dernière glycémie",
          "Résumer à l'état actuel.",
          "L'équipe perd l'évolution et les éléments expliquant la prise en charge.",
          false,
          effect(-7, -4, 40, { isError: true }),
        ),
      ],
    }),
  ],
};

const roadTrauma: InterventionScenario = {
  id: "road-trauma-24",
  specialty: "Traumatologie",
  title: "Collision scooter contre voiture",
  summary: "Un homme de 24 ans est au sol après une collision, dans une circulation encore active.",
  difficulty: "advanced",
  estimatedMinutes: 12,
  baseXp: 220,
  illustration: "trauma",
  unlockAfter: "hypoglycemia-72",
  startingPatient: 44,
  alert: {
    patient: "Homme, 24 ans",
    reason: "Accident de la voie publique",
    priority: "Traumatisme à haute cinétique",
    distance: "6,8 km",
    location: "Avenue de la République",
    time: "18:06",
    dispatchNote:
      "Circulation dense. Victime au sol, consciente selon témoin. Forces de l'ordre en route.",
  },
  reward: {
    coins: 190,
    chest: "Coffre Or",
    chestMinimumScore: 80,
    badge: "Chef d'intervention",
    badgeMinimumScore: 93,
  },
  pulseAdvice: [
    "Sur accident de circulation, la sécurité de la zone précède toujours l'approche de la victime.",
    "Recherche et traite d'abord les menaces vitales ; les lésions impressionnantes ne sont pas toujours prioritaires.",
    "Anticipe le transport et transmets le mécanisme de l'accident, l'évolution et les gestes réalisés.",
  ],
  steps: [
    step({
      id: "trauma-arrival",
      phase: "arrival",
      eyebrow: "Approche routière",
      title: "Positionner le véhicule",
      narrative: "La circulation contourne la victime et le scooter occupe une voie.",
      objective: "Protéger l'équipe avant toute sortie du véhicule.",
      patient: patient("Victime à distance", "Mouvements visibles au sol.", "critical", [
        { label: "Trafic", value: "Actif", tone: "critical" },
        { label: "Renforts", value: "En approche" },
      ]),
      choices: [
        choice(
          "trauma-arrival-shield",
          "Créer une zone de protection",
          "Positionner selon procédure, signaler et coordonner la circulation.",
          "L'équipe dispose d'un corridor d'approche plus sûr.",
          true,
          effect(12, 4, 55, { xpBonus: 10 }),
        ),
        choice(
          "trauma-arrival-run",
          "Courir directement vers la victime",
          "Gagner quelques secondes avant les forces de l'ordre.",
          "L'équipe s'expose au suraccident, ce qui compromet toute la mission.",
          false,
          effect(-20, -15, 20, { isError: true }),
        ),
      ],
    }),
    step({
      id: "trauma-safety",
      phase: "safety",
      eyebrow: "Zone d'intervention",
      title: "Contrôler les dangers",
      narrative: "Du carburant s'écoule près du scooter. Des témoins se rapprochent.",
      objective: "Identifier les dangers et demander les moyens adaptés.",
      patient: patient("Victime exposée", "Casque en place, respiration visible.", "critical", [
        { label: "Carburant", value: "Fuite", tone: "critical" },
        { label: "Témoins", value: "Nombreux", tone: "watch" },
      ]),
      choices: [
        choice(
          "trauma-safety-coordinate",
          "Baliser et demander sécurisation",
          "Éloigner les témoins, signaler la fuite et coordonner les renforts.",
          "Les dangers sont signalés et l'approche devient contrôlée.",
          true,
          effect(12, 5, 60, { xpBonus: 10 }),
        ),
        choice(
          "trauma-safety-ignore",
          "Ignorer la fuite",
          "Se concentrer uniquement sur le patient.",
          "Le risque environnemental menace le patient et les intervenants.",
          false,
          effect(-18, -12, 30, { isError: true }),
        ),
      ],
    }),
    step({
      id: "trauma-primary",
      phase: "primary",
      eyebrow: "Contact victime",
      title: "Prioriser les détresses",
      narrative:
        "Le patient gémit, respire rapidement et présente un saignement abondant à la cuisse.",
      objective: "Réaliser un bilan primaire adapté au traumatisme et contrôler l'hémorragie.",
      patient: patient(
        "Traumatisé instable",
        "Pâleur, agitation et douleur du bassin.",
        "critical",
        [
          { label: "FR", value: "30/min", tone: "critical" },
          { label: "Pouls", value: "132/min", tone: "critical" },
          { label: "Hémorragie", value: "Active", tone: "critical" },
          { label: "Conscience", value: "Confus", tone: "critical" },
        ],
      ),
      choices: [
        choice(
          "trauma-primary-bleeding",
          "Contrôler l'hémorragie et faire ABCDE",
          "Traiter la menace immédiate tout en maintenant l'axe et l'évaluation vitale.",
          "La menace hémorragique est prise en charge dans une évaluation structurée.",
          true,
          effect(15, 16, 90, { xpBonus: 15, flags: ["bleeding-controlled"] }),
        ),
        choice(
          "trauma-primary-leg",
          "Examiner la jambe en détail",
          "Rechercher précisément la fracture avant le reste du bilan.",
          "L'examen lésionnel détaillé retarde le contrôle des menaces vitales.",
          false,
          effect(-16, -20, 95, { isError: true }),
        ),
        choice(
          "trauma-primary-helmet",
          "Retirer immédiatement le casque seul",
          "Faciliter l'interrogatoire.",
          "Toute manœuvre doit être justifiée, coordonnée et réalisée en maintenant l'axe selon les procédures.",
          false,
          effect(-14, -16, 55, { isError: true }),
        ),
      ],
    }),
    step({
      id: "trauma-secondary",
      phase: "secondary",
      eyebrow: "Mécanisme et lésions",
      title: "Compléter sans retarder",
      narrative:
        "L'hémorragie est contrôlée. Le patient indique une douleur thoracique et pelvienne.",
      objective: "Recueillir le mécanisme, examiner rapidement et réévaluer les constantes.",
      patient: patient("Risque de choc", "Collision latérale à vitesse importante.", "critical", [
        { label: "TA", value: "92/58 mmHg", tone: "critical" },
        { label: "Pouls", value: "124/min", tone: "critical" },
        { label: "Bassin", value: "Douloureux", tone: "critical" },
      ]),
      choices: [
        choice(
          "trauma-secondary-fast",
          "Faire un bilan secondaire ciblé",
          "Rechercher mécanisme, douleur, lésions majeures et évolution sans retarder l'évacuation.",
          "Le bilan identifie un traumatisme potentiellement sévère et reste compatible avec l'urgence.",
          true,
          effect(11, 7, 100, { xpBonus: 10 }),
        ),
        choice(
          "trauma-secondary-full",
          "Faire un examen très détaillé sur place",
          "Tester chaque articulation avant de transmettre.",
          "L'exhaustivité retarde l'orientation d'un patient instable.",
          false,
          effect(-9, -12, 190, { isError: true }),
        ),
      ],
    }),
    step({
      id: "trauma-care",
      phase: "care",
      eyebrow: "Immobilisation et surveillance",
      title: "Choisir les gestes prioritaires",
      narrative: "Le patient reste agité et tente de se relever.",
      objective: "Prévenir l'aggravation et préparer une évacuation adaptée.",
      patient: patient(
        "Instabilité persistante",
        "La douleur et l'hypoperfusion majorent l'agitation.",
        "critical",
        [
          { label: "Comportement", value: "Agité", tone: "watch" },
          { label: "Perfusion", value: "Altérée", tone: "critical" },
        ],
      ),
      choices: [
        choice(
          "trauma-care-axis",
          "Maintenir, rassurer et immobiliser selon procédure",
          "Poursuivre surveillance et contrôle de l'hémorragie.",
          "Les gestes limitent les mouvements et préparent le transport en sécurité.",
          true,
          effect(12, 10, 105, { xpBonus: 12, rewardBonus: 15 }),
        ),
        choice(
          "trauma-care-stand",
          "Aider le patient à se relever",
          "Évaluer s'il peut marcher jusqu'au brancard.",
          "Le mécanisme, l'instabilité et la douleur pelvienne rendent cette mobilisation dangereuse.",
          false,
          effect(-20, -22, 45, { isError: true }),
        ),
      ],
    }),
    step({
      id: "trauma-decision",
      phase: "decision",
      eyebrow: "Demande de renfort",
      title: "Transmettre la gravité",
      narrative: "La régulation demande un bilan synthétique et la cinétique de l'accident.",
      objective: "Hiérarchiser mécanisme, menaces vitales, constantes et réponse aux gestes.",
      patient: patient(
        "Traumatisme sévère suspecté",
        "La destination dépend de la gravité et de la filière disponible.",
        "critical",
        [
          { label: "Hémorragie", value: "Contrôlée" },
          { label: "Hémodynamique", value: "Précaire", tone: "critical" },
        ],
      ),
      choices: [
        choice(
          "trauma-decision-full",
          "Transmettre mécanisme et ABCDE",
          "Signaler instabilité, hémorragie, douleurs thoracique et pelvienne, gestes et évolution.",
          "La régulation peut engager les renforts et la filière traumatologique adaptés.",
          true,
          effect(14, 10, 75, { xpBonus: 14, rewardBonus: 20 }),
        ),
        choice(
          "trauma-decision-injury",
          "Parler seulement de la jambe",
          "Décrire la fracture visible avec précision.",
          "La lésion visible masque les signes de choc et le risque de traumatisme multiple.",
          false,
          effect(-15, -16, 70, { isError: true }),
        ),
      ],
    }),
    step({
      id: "trauma-transport",
      phase: "transport",
      eyebrow: "Évacuation rapide",
      title: "Coordonner le départ",
      narrative: "Les renforts sécurisent la route. La filière confirme l'accueil du patient.",
      objective: "Limiter le temps sur place tout en maintenant les mesures de sécurité.",
      patient: patient(
        "Prêt pour l'évacuation",
        "Chaque transfert doit préserver l'axe et les dispositifs.",
        "watch",
        [
          { label: "Temps sur place", value: "À limiter", tone: "watch" },
          { label: "Surveillance", value: "Continue" },
        ],
      ),
      choices: [
        choice(
          "trauma-transport-team",
          "Faire un relevage coordonné",
          "Brief court, rôles distribués, matériel vérifié et réévaluation après transfert.",
          "Le départ est rapide, coordonné et sans rupture de surveillance.",
          true,
          effect(12, 8, 130, { xpBonus: 12, rewardBonus: 15 }),
        ),
        choice(
          "trauma-transport-rush",
          "Relever sans briefing",
          "Agir au plus vite puisque la route est libre.",
          "L'absence de coordination augmente les mouvements et le risque de perte de matériel.",
          false,
          effect(-12, -14, 75, { isError: true }),
        ),
      ],
    }),
    step({
      id: "trauma-handover",
      phase: "debrief",
      eyebrow: "Accueil trauma",
      title: "Faire le relais",
      narrative:
        "L'équipe hospitalière demande le mécanisme, la chronologie et la réponse aux gestes.",
      objective: "Transmettre sans perdre les informations critiques.",
      patient: patient(
        "Relais spécialisé",
        "Le patient est pris en charge par l'équipe receveuse.",
        "stable",
        [
          { label: "Relais", value: "Équipe prête" },
          { label: "Traçabilité", value: "Complète" },
        ],
      ),
      choices: [
        choice(
          "trauma-handover-chrono",
          "Faire un relais chronologique structuré",
          "Mécanisme, état initial, évolution, gestes, constantes et événements du transport.",
          "Le relais donne une vision complète et immédiatement exploitable.",
          true,
          effect(11, 4, 90, { xpBonus: 12, rewardBonus: 20 }),
        ),
        choice(
          "trauma-handover-paper",
          "Déposer la fiche et repartir",
          "L'équipe peut lire les éléments plus tard.",
          "Une situation critique nécessite un relais oral ciblé en plus de la traçabilité écrite.",
          false,
          effect(-8, -5, 45, { isError: true }),
        ),
      ],
    }),
  ],
};

export const INTERVENTION_SCENARIOS: InterventionScenario[] = [chestPain, hypoglycemia, roadTrauma];

export function getInterventionScenario(scenarioId: string) {
  return INTERVENTION_SCENARIOS.find((scenario) => scenario.id === scenarioId);
}
