/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PulseRouteImport } from './routes/pulse'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeconLessonIdRouteImport } from './routes/lecon.$lessonId'
import { Route as ApiPulseRouteImport } from './routes/api/pulse'

const PulseRoute = PulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeconLessonIdRoute = LeconLessonIdRouteImport.update({
  id: '/lecon/$lessonId',
  path: '/lecon/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPulseRoute = ApiPulseRouteImport.update({
  id: '/api/pulse',
  path: '/api/pulse',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/profil': typeof ProfilRoute
  '/pulse': typeof PulseRoute
  '/api/pulse': typeof ApiPulseRoute
  '/lecon/$lessonId': typeof LeconLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/profil': typeof ProfilRoute
  '/pulse': typeof PulseRoute
  '/api/pulse': typeof ApiPulseRoute
  '/lecon/$lessonId': typeof LeconLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/profil': typeof ProfilRoute
  '/pulse': typeof PulseRoute
  '/api/pulse': typeof ApiPulseRoute
  '/lecon/$lessonId': typeof LeconLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/profil'
    | '/pulse'
    | '/api/pulse'
    | '/lecon/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/profil'
    | '/pulse'
    | '/api/pulse'
    | '/lecon/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/onboarding'
    | '/profil'
    | '/pulse'
    | '/api/pulse'
    | '/lecon/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfilRoute: typeof ProfilRoute
  PulseRoute: typeof PulseRoute
  ApiPulseRoute: typeof ApiPulseRoute
  LeconLessonIdRoute: typeof LeconLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pulse': {
      id: '/pulse'
      path: '/pulse'
      fullPath: '/pulse'
      preLoaderRoute: typeof PulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecon/$lessonId': {
      id: '/lecon/$lessonId'
      path: '/lecon/$lessonId'
      fullPath: '/lecon/$lessonId'
      preLoaderRoute: typeof LeconLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pulse': {
      id: '/api/pulse'
      path: '/api/pulse'
      fullPath: '/api/pulse'
      preLoaderRoute: typeof ApiPulseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  ProfilRoute: ProfilRoute,
  PulseRoute: PulseRoute,
  ApiPulseRoute: ApiPulseRoute,
  LeconLessonIdRoute: LeconLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
