/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeconLessonIdRouteImport } from './routes/lecon.$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeconLessonIdRoute = LeconLessonIdRouteImport.update({
  id: '/lecon/$lessonId',
  path: '/lecon/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lecon/$lessonId': typeof LeconLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lecon/$lessonId': typeof LeconLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lecon/$lessonId': typeof LeconLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lecon/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lecon/$lessonId'
  id: '__root__' | '/' | '/lecon/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeconLessonIdRoute: typeof LeconLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecon/$lessonId': {
      id: '/lecon/$lessonId'
      path: '/lecon/$lessonId'
      fullPath: '/lecon/$lessonId'
      preLoaderRoute: typeof LeconLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeconLessonIdRoute: LeconLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
